# Generated by Django 5.2.15 on 2026-06-22 07:03

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=100)),
                ("entity_slug", models.SlugField(max_length=63)),
                ("page_config", models.JSONField(default=dict)),
                ("blocks", models.JSONField(default=list)),
                ("line_items", models.JSONField(default=dict)),
                ("version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "document_templates",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "entity_slug"],
                        name="document_te_workspa_b99b9a_idx",
                    )
                ],
                "unique_together": {("workspace_id", "slug")},
            },
        ),
    ]
