# Generated by Django 5.2.15 on 2026-06-24 10:59

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KPIDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="general", max_length=40)),
                ("source_type", models.CharField(default="nql", max_length=10)),
                ("nql_source", models.TextField(blank=True)),
                ("value_field", models.CharField(blank=True, max_length=64)),
                ("aggregate", models.CharField(default="sum", max_length=10)),
                ("native_key", models.CharField(blank=True, max_length=64)),
                (
                    "target",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "warning_threshold",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "critical_threshold",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("direction", models.CharField(default="higher_better", max_length=15)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("owner", models.CharField(blank=True, max_length=64)),
                (
                    "refresh_strategy",
                    models.CharField(default="on_demand", max_length=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_system", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "analytics_kpi_definitions",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "category", "is_active"],
                        name="analytics_k_workspa_fc0f5b_idx",
                    )
                ],
                "unique_together": {("workspace_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="KPISnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("kpi_id", models.UUIDField(db_index=True)),
                ("code", models.SlugField(max_length=64)),
                (
                    "value",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "target",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("status", models.CharField(default="unknown", max_length=15)),
                ("period", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "analytics_kpi_snapshots",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "code", "-created_at"],
                        name="analytics_k_workspa_56352e_idx",
                    )
                ],
            },
        ),
    ]
