# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('spam', 'Spam')], default='pending', max_length=15)),
                ('data', models.JSONField()),
                ('created_record_id', models.UUIDField(blank=True, null=True)),
                ('submitter_name', models.CharField(blank=True, max_length=255)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitter_user_agent', models.CharField(blank=True, max_length=500)),
                ('portal_user_id', models.UUIDField(blank=True, null=True)),
                ('honeypot_triggered', models.BooleanField(default=False)),
                ('spam_score', models.FloatField(default=0.0)),
                ('validation_errors', models.JSONField(default=list)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'form_submissions',
                'indexes': [models.Index(fields=['workspace_id', 'form_id', '-created_at'], name='form_submis_workspa_d8f2ee_idx'), models.Index(fields=['workspace_id', 'status'], name='form_submis_workspa_79fefb_idx')],
            },
        ),
    ]
