# Generated by Django 5.2.15 on 2026-06-24 08:43

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetValuationSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("asset_record_id", models.UUIDField(db_index=True)),
                ("snapshot_date", models.DateField()),
                (
                    "purchase_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "book_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
            ],
            options={
                "db_table": "asset_valuation_snapshots",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "asset_record_id", "-snapshot_date"],
                        name="asset_valua_workspa_1ad112_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DepreciationEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("schedule_id", models.UUIDField(db_index=True)),
                ("asset_record_id", models.UUIDField(db_index=True)),
                ("period_index", models.IntegerField(default=0)),
                ("period_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "accumulated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "net_book_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("posted", models.BooleanField(default=True)),
                ("journal_entry_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "asset_depreciation_entries",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "asset_record_id", "period_index"],
                        name="asset_depre_workspa_9966cc_idx",
                    )
                ],
                "unique_together": {("workspace_id", "schedule_id", "period_index")},
            },
        ),
        migrations.CreateModel(
            name="DepreciationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("asset_record_id", models.UUIDField(db_index=True)),
                ("method", models.CharField(default="straight_line", max_length=30)),
                (
                    "acquisition_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "salvage_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("useful_life_months", models.IntegerField(default=12)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("gl_expense_account", models.CharField(default="6100", max_length=32)),
                (
                    "gl_accumulated_account",
                    models.CharField(default="1600", max_length=32),
                ),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "db_table": "asset_depreciation_schedules",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "asset_record_id", "status"],
                        name="asset_depre_workspa_5d659b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DisposalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("asset_record_id", models.UUIDField(db_index=True)),
                ("kind", models.CharField(default="disposal", max_length=20)),
                ("method", models.CharField(default="sale", max_length=20)),
                ("disposal_date", models.DateField(blank=True, null=True)),
                (
                    "proceeds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "book_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "gain_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "residual_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("reason", models.TextField(blank=True)),
                ("status", models.CharField(default="posted", max_length=20)),
                ("journal_entry_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "asset_disposal_records",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "asset_record_id"],
                        name="asset_dispo_workspa_0832a3_idx",
                    )
                ],
            },
        ),
    ]
