# Generated by Django 5.2.15 on 2026-06-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_seed_assets_template"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="disposalrecord",
            unique_together={("workspace_id", "asset_record_id", "kind")},
        ),
    ]
