# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('view_definition_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('member_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('hidden_field_slugs', models.JSONField(default=list)),
                ('column_widths', models.JSONField(default=dict)),
                ('personal_filters', models.JSONField(default=list)),
                ('sort_overrides', models.JSONField(default=list)),
                ('group_by_override', models.CharField(blank=True, max_length=100)),
                ('is_pinned', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'saved_views',
                'indexes': [models.Index(fields=['workspace_id', 'member_id'], name='saved_views_workspa_c13097_idx')],
                'unique_together': {('workspace_id', 'view_definition_id', 'member_id')},
            },
        ),
    ]
