# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('definition_id', models.UUIDField(db_index=True)),
                ('source_entity_id', models.UUIDField()),
                ('source_record_id', models.UUIDField(db_index=True)),
                ('target_entity_id', models.UUIDField()),
                ('target_record_id', models.UUIDField(db_index=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'record_relationships',
                'indexes': [models.Index(fields=['workspace_id', 'source_record_id'], name='record_rela_workspa_5f73af_idx'), models.Index(fields=['workspace_id', 'target_record_id'], name='record_rela_workspa_3872cd_idx')],
                'unique_together': {('workspace_id', 'definition_id', 'source_record_id', 'target_record_id')},
            },
        ),
        migrations.CreateModel(
            name='RelationshipDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('source_entity_id', models.UUIDField(db_index=True)),
                ('source_field_slug', models.CharField(blank=True, max_length=100)),
                ('target_entity_id', models.UUIDField(db_index=True)),
                ('target_field_slug', models.CharField(blank=True, max_length=100)),
                ('cardinality', models.CharField(choices=[('one_to_one', 'One-to-One'), ('one_to_many', 'One-to-Many'), ('many_to_many', 'Many-to-Many')], max_length=20)),
                ('junction_table', models.CharField(blank=True, max_length=63)),
                ('on_delete', models.CharField(choices=[('protect', 'Protect'), ('cascade', 'Cascade'), ('set_null', 'Set Null'), ('detach', 'Detach')], default='detach', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'relationship_definitions',
                'indexes': [models.Index(fields=['workspace_id', 'source_entity_id'], name='relationshi_workspa_db75c3_idx'), models.Index(fields=['workspace_id', 'target_entity_id'], name='relationshi_workspa_a0e59c_idx')],
                'unique_together': {('workspace_id', 'source_entity_id', 'slug')},
            },
        ),
    ]
