# Generated by Django 5.2.15 on 2026-06-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationshipdefinition",
            name="cardinality",
            field=models.CharField(
                choices=[
                    ("one_to_one", "One-to-One"),
                    ("one_to_many", "One-to-Many"),
                    ("many_to_many", "Many-to-Many"),
                    ("self_ref", "Self-Referencing"),
                ],
                max_length=20,
            ),
        ),
    ]
