# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleBinEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('entity_slug', models.CharField(max_length=63)),
                ('record_id', models.UUIDField(db_index=True)),
                ('record_title', models.CharField(blank=True, max_length=500)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(db_index=True)),
                ('purge_after', models.DateTimeField(db_index=True)),
                ('cascade_entries', models.JSONField(default=list)),
                ('is_purged', models.BooleanField(default=False)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recycle_bin_entries',
                'indexes': [models.Index(fields=['workspace_id', 'is_purged', 'purge_after'], name='recycle_bin_workspa_dd2d6e_idx')],
                'unique_together': {('workspace_id', 'record_id')},
            },
        ),
    ]
