# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('plural_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=63)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('table_name', models.CharField(blank=True, max_length=127)),
                ('has_physical_table', models.BooleanField(default=False)),
                ('enable_activity', models.BooleanField(default=True)),
                ('enable_comments', models.BooleanField(default=True)),
                ('enable_attachments', models.BooleanField(default=True)),
                ('enable_tagging', models.BooleanField(default=True)),
                ('enable_recycle_bin', models.BooleanField(default=True)),
                ('enable_versioning', models.BooleanField(default=False)),
                ('record_owner_field', models.CharField(blank=True, max_length=63)),
                ('current_schema_version', models.IntegerField(default=1)),
                ('settings', models.JSONField(default=dict)),
                ('title_field_slug', models.CharField(default='name', max_length=63)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entity_definitions',
            },
        ),
        migrations.CreateModel(
            name='EntityPhysicalTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('table_name', models.CharField(max_length=127)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('ready', 'Ready'), ('migrating', 'Migrating'), ('error', 'Error')], default='provisioning', max_length=30)),
                ('promoted_columns', models.JSONField(default=list)),
                ('last_projection_event_id', models.UUIDField(blank=True, null=True)),
                ('row_count', models.BigIntegerField(default=0)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_table', to='metadata.entitydefinition')),
            ],
            options={
                'db_table': 'entity_physical_tables',
            },
        ),
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('layout', models.JSONField(default=list)),
                ('settings', models.JSONField(default=dict)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='metadata.entitydefinition')),
            ],
            options={
                'db_table': 'form_definitions',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=63)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('settings', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'modules',
                'unique_together': {('workspace_id', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='entitydefinition',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='metadata.module'),
        ),
        migrations.CreateModel(
            name='SchemaVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('version', models.IntegerField()),
                ('snapshot', models.JSONField()),
                ('migration_sql', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.UUIDField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('parent_version', models.IntegerField(blank=True, null=True)),
                ('commit_id', models.UUIDField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_versions', to='metadata.entitydefinition')),
            ],
            options={
                'db_table': 'schema_versions',
            },
        ),
        migrations.CreateModel(
            name='ViewDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('view_type', models.CharField(choices=[('table', 'Table'), ('kanban', 'Kanban'), ('calendar', 'Calendar'), ('gantt', 'Gantt'), ('gallery', 'Gallery'), ('map', 'Map'), ('timeline', 'Timeline'), ('form', 'Form')], default='table', max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='metadata.entitydefinition')),
            ],
            options={
                'db_table': 'view_definitions',
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=63)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long Text'), ('rich_text', 'Rich Text'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('currency', 'Currency'), ('percent', 'Percent'), ('date', 'Date'), ('datetime', 'Date & Time'), ('time', 'Time'), ('duration', 'Duration'), ('boolean', 'Checkbox'), ('select', 'Single Select'), ('multi_select', 'Multi Select'), ('status', 'Status'), ('lookup', 'Lookup (FK)'), ('multi_lookup', 'Multi Lookup (M2M)'), ('user', 'User'), ('multi_user', 'Multi User'), ('file', 'File'), ('image', 'Image'), ('formula', 'Formula'), ('rollup', 'Rollup'), ('count', 'Count'), ('created_at', 'Created At'), ('updated_at', 'Updated At'), ('created_by', 'Created By'), ('updated_by', 'Updated By'), ('auto_number', 'Auto Number'), ('uuid', 'UUID'), ('json', 'JSON'), ('rating', 'Rating'), ('progress', 'Progress'), ('location', 'Location'), ('barcode', 'Barcode / QR')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_promoted', models.BooleanField(default=False)),
                ('column_name', models.CharField(blank=True, max_length=63)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_sortable', models.BooleanField(default=True)),
                ('is_searchable', models.BooleanField(default=False)),
                ('has_index', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('validation_rules', models.JSONField(default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_readonly', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('config', models.JSONField(default=dict)),
                ('read_roles', models.JSONField(default=list)),
                ('write_roles', models.JSONField(default=list)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='metadata.entitydefinition')),
            ],
            options={
                'db_table': 'field_definitions',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['entity', 'is_promoted'], name='field_defin_entity__f4e57a_idx'), models.Index(fields=['workspace_id'], name='field_defin_workspa_aecfc2_idx')],
                'unique_together': {('entity', 'slug')},
            },
        ),
        migrations.AddIndex(
            model_name='entitydefinition',
            index=models.Index(fields=['workspace_id', 'is_active'], name='entity_defi_workspa_e5b726_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitydefinition',
            unique_together={('workspace_id', 'slug')},
        ),
        migrations.AddIndex(
            model_name='schemaversion',
            index=models.Index(fields=['entity', 'is_current'], name='schema_vers_entity__4e7c6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schemaversion',
            unique_together={('entity', 'version')},
        ),
    ]
