# Generated by Django 5.2.15 on 2026-06-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fielddefinition",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
