# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('trigger_on', models.CharField(choices=[('before_create', 'Before Create'), ('after_create', 'After Create'), ('before_update', 'Before Update'), ('after_update', 'After Update'), ('before_delete', 'Before Delete'), ('after_delete', 'After Delete'), ('field_changed', 'Specific Field Changed')], max_length=25)),
                ('watch_field_slug', models.CharField(blank=True, max_length=100)),
                ('condition_nql', models.TextField(blank=True)),
                ('actions', models.JSONField(default=list)),
                ('priority', models.IntegerField(default=100)),
                ('run_all', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('eval_count', models.BigIntegerField(default=0)),
                ('match_count', models.BigIntegerField(default=0)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'business_rules',
                'indexes': [models.Index(fields=['workspace_id', 'entity_id', 'is_active', 'priority'], name='business_ru_workspa_6d491e_idx')],
                'unique_together': {('workspace_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='RuleExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('record_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField()),
                ('trigger_on', models.CharField(max_length=25)),
                ('condition_matched', models.BooleanField()),
                ('actions_executed', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rule_execution_logs',
                'indexes': [models.Index(fields=['rule_id', '-executed_at'], name='rule_execut_rule_id_0f5736_idx'), models.Index(fields=['workspace_id', 'record_id'], name='rule_execut_workspa_3add4e_idx')],
            },
        ),
    ]
