# Generated by Django 5.2.15 on 2026-06-23 11:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "db_table": "inv_locations",
            },
        ),
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="inventory.itemcategory",
                    ),
                ),
            ],
            options={
                "db_table": "inv_item_categories",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("uom", models.CharField(default="ea", max_length=20)),
                (
                    "valuation_method",
                    models.CharField(
                        choices=[
                            ("fifo", "FIFO"),
                            ("average", "Weighted average"),
                            ("standard", "Standard cost"),
                        ],
                        default="average",
                        max_length=10,
                    ),
                ),
                (
                    "standard_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("track_inventory", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("inventory_account_code", models.CharField(blank=True, max_length=32)),
                ("cogs_account_code", models.CharField(blank=True, max_length=32)),
                ("description", models.TextField(blank=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.itemcategory",
                    ),
                ),
            ],
            options={
                "db_table": "inv_items",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "inv_warehouses",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "code"],
                        name="inv_warehou_workspa_f3e292_idx",
                    )
                ],
                "unique_together": {("workspace_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt"),
                            ("issue", "Issue"),
                            ("adjustment", "Adjustment"),
                            ("transfer_in", "Transfer in"),
                            ("transfer_out", "Transfer out"),
                        ],
                        max_length=12,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "on_hand_after",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("occurred_at", models.DateTimeField()),
                ("reference", models.CharField(blank=True, max_length=128)),
                ("memo", models.CharField(blank=True, max_length=300)),
                ("journal_entry_id", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.location",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inv_stock_movements",
            },
        ),
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                (
                    "on_hand",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "avg_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="inventory.item",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inv_stock_levels",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="inventory.warehouse",
            ),
        ),
        migrations.CreateModel(
            name="FIFOLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("received_at", models.DateTimeField()),
                ("original_qty", models.DecimalField(decimal_places=4, max_digits=20)),
                ("remaining", models.DecimalField(decimal_places=4, max_digits=20)),
                ("unit_cost", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fifo_layers",
                        to="inventory.item",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fifo_layers",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inv_fifo_layers",
            },
        ),
        migrations.AddIndex(
            model_name="itemcategory",
            index=models.Index(
                fields=["workspace_id", "name"], name="inv_item_ca_workspa_e6bb54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["workspace_id", "sku"], name="inv_items_workspa_49af30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["workspace_id", "name"], name="inv_items_workspa_191943_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("workspace_id", "sku")},
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["workspace_id", "item", "warehouse", "occurred_at"],
                name="inv_stock_m_workspa_a1fa7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["workspace_id", "movement_type"],
                name="inv_stock_m_workspa_5ee265_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocklevel",
            index=models.Index(
                fields=["workspace_id", "item", "warehouse"],
                name="inv_stock_l_workspa_5a2568_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stocklevel",
            unique_together={("workspace_id", "item", "warehouse")},
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["workspace_id", "warehouse"],
                name="inv_locatio_workspa_967614_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("workspace_id", "warehouse", "code")},
        ),
        migrations.AddIndex(
            model_name="fifolayer",
            index=models.Index(
                fields=["workspace_id", "item", "warehouse", "received_at"],
                name="inv_fifo_la_workspa_43dd1c_idx",
            ),
        ),
    ]
