# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('layout', models.JSONField(default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('shared_with', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'dashboards',
                'unique_together': {('workspace_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('widget_type', models.CharField(choices=[('report', 'Report / Chart'), ('metric_card', 'Metric Card (KPI)'), ('iframe', 'Embedded iFrame'), ('text', 'Text / Markdown'), ('activity_feed', 'Activity Feed'), ('quick_links', 'Quick Links')], max_length=25)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('report_id', models.UUIDField(blank=True, null=True)),
                ('grid_x', models.IntegerField(default=0)),
                ('grid_y', models.IntegerField(default=0)),
                ('grid_w', models.IntegerField(default=6)),
                ('grid_h', models.IntegerField(default=4)),
                ('config', models.JSONField(default=dict)),
                ('refresh_interval_seconds', models.IntegerField(default=0)),
                ('source_report_ids', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'indexes': [models.Index(fields=['dashboard_id'], name='dashboard_w_dashboa_76f849_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('table', 'Table'), ('chart', 'Chart'), ('pivot', 'Pivot Table'), ('funnel', 'Funnel'), ('cohort', 'Cohort'), ('kanban_summary', 'Kanban Summary'), ('timeline', 'Timeline')], default='table', max_length=25)),
                ('nql_ast', models.JSONField()),
                ('nql_source', models.TextField(blank=True)),
                ('display_config', models.JSONField(default=dict)),
                ('source_entity_ids', models.JSONField(default=list)),
                ('schedule_cron', models.CharField(blank=True, max_length=100)),
                ('schedule_recipients', models.JSONField(default=list)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('shared_with', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'reports',
                'unique_together': {('workspace_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('row_count', models.IntegerField(default=0)),
                ('data', models.JSONField(default=list)),
                ('generated_by', models.UUIDField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'report_snapshots',
                'indexes': [models.Index(fields=['report_id', '-created_at'], name='report_snap_report__f17c30_idx')],
            },
        ),
    ]
