# Generated by Django 5.2.15 on 2026-06-24 12:04

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=80)),
                ("env_type", models.CharField(default="dev", max_length=10)),
                ("branch", models.CharField(max_length=100)),
                ("sequence", models.IntegerField(default=0)),
                ("is_production", models.BooleanField(default=False)),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "db_table": "promotion_environments",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "sequence"],
                        name="promotion_e_workspa_0011da_idx",
                    )
                ],
                "unique_together": {("workspace_id", "env_type")},
            },
        ),
        migrations.CreateModel(
            name="PromotionApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("package_id", models.UUIDField(db_index=True)),
                ("role", models.CharField(default="approver", max_length=30)),
                ("approver_id", models.UUIDField(blank=True, null=True)),
                ("decision", models.CharField(default="approved", max_length=20)),
                ("comment", models.TextField(blank=True)),
            ],
            options={
                "db_table": "promotion_approvals",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "package_id"],
                        name="promotion_a_workspa_8a43aa_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PromotionPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=150)),
                ("version", models.CharField(default="1", max_length=20)),
                ("source_env_id", models.UUIDField(db_index=True)),
                ("target_env_id", models.UUIDField(db_index=True)),
                ("status", models.CharField(default="draft", max_length=20)),
                ("object_refs", models.JSONField(default=list)),
                ("diff", models.JSONField(default=dict)),
                ("risk_summary", models.JSONField(default=dict)),
                ("precheck", models.JSONField(default=dict)),
                ("package_hash", models.CharField(blank=True, max_length=64)),
                ("source_sha", models.CharField(blank=True, max_length=64)),
                ("target_sha_before", models.CharField(blank=True, max_length=64)),
                ("merge_commit_sha", models.CharField(blank=True, max_length=64)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("approved_by", models.UUIDField(blank=True, null=True)),
                ("executed_by", models.UUIDField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "promotion_packages",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "status"],
                        name="promotion_p_workspa_c7dccc_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "target_env_id", "status"],
                        name="promotion_p_workspa_dd1241_idx",
                    ),
                ],
            },
        ),
    ]
