# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('head_sha', models.CharField(max_length=64)),
                ('base_sha', models.CharField(blank=True, max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('is_protected', models.BooleanField(default=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'config_branches',
                'unique_together': {('workspace_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ConfigCommit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('sha', models.CharField(db_index=True, max_length=64)),
                ('parent_sha', models.CharField(blank=True, max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('payload', models.JSONField()),
                ('diff', models.JSONField(default=dict)),
                ('author_id', models.UUIDField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'config_commits',
                'indexes': [models.Index(fields=['workspace_id', 'branch', '-created_at'], name='config_comm_workspa_efd976_idx')],
                'unique_together': {('workspace_id', 'sha')},
            },
        ),
        migrations.CreateModel(
            name='ConfigMergeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_branch', models.CharField(max_length=100)),
                ('target_branch', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed'), ('conflict', 'Conflict')], default='open', max_length=20)),
                ('conflict_details', models.JSONField(default=list)),
                ('resolution', models.JSONField(default=dict)),
                ('opened_by', models.UUIDField()),
                ('merged_by', models.UUIDField(blank=True, null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('merge_commit_sha', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'config_merge_requests',
                'indexes': [models.Index(fields=['workspace_id', 'status'], name='config_merg_workspa_4a6d8e_idx')],
            },
        ),
    ]
