# Generated by Django 5.2.15 on 2026-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_seed_projects_template"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectcostentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference__gt", "")),
                fields=("workspace_id", "project_record_id", "source", "reference"),
                name="uq_project_cost_reference",
            ),
        ),
    ]
