# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('record_created', 'Record Created'), ('record_updated', 'Record Updated'), ('record_deleted', 'Record Deleted'), ('field_changed', 'Field Changed'), ('schedule', 'Scheduled (CRON)'), ('webhook', 'Incoming Webhook'), ('manual', 'Manual / Button'), ('stage_entered', 'Stage Entered'), ('sla_breached', 'SLA Breached'), ('form_submitted', 'Form Submitted')], max_length=50)),
                ('trigger_config', models.JSONField(default=dict)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('module_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('is_system', models.BooleanField(default=False)),
                ('max_concurrent_runs', models.IntegerField(default=10)),
                ('timeout_seconds', models.IntegerField(default=3600)),
                ('retry_policy', models.JSONField(default=dict)),
                ('run_count', models.BigIntegerField(default=0)),
                ('error_count', models.BigIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_definitions',
                'unique_together': {('workspace_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField()),
                ('source_step_id', models.UUIDField(db_index=True)),
                ('target_step_id', models.UUIDField(db_index=True)),
                ('condition_label', models.CharField(blank=True, max_length=50)),
                ('condition_expr', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'workflow_edges',
                'indexes': [models.Index(fields=['workflow_id'], name='workflow_ed_workflo_0b15f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('trigger_type', models.CharField(max_length=50)),
                ('trigger_payload', models.JSONField(default=dict)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('record_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timed_out', 'Timed Out')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('error_step_id', models.UUIDField(blank=True, null=True)),
                ('context', models.JSONField(default=dict)),
                ('initiated_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_runs',
                'indexes': [models.Index(fields=['workspace_id', 'workflow_id'], name='workflow_ru_workspa_b7f91d_idx'), models.Index(fields=['workspace_id', 'record_id'], name='workflow_ru_workspa_8ef09e_idx'), models.Index(fields=['status', 'started_at'], name='workflow_ru_status_7909e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('step_type', models.CharField(choices=[('action_update_record', 'Update Record'), ('action_create_record', 'Create Record'), ('action_delete_record', 'Delete Record'), ('action_send_email', 'Send Email'), ('action_send_notification', 'Send In-App Notification'), ('action_send_webhook', 'Send Webhook'), ('action_call_api', 'HTTP API Call'), ('action_run_workflow', 'Run Sub-Workflow'), ('action_run_script', 'Run Server Script'), ('action_assign', 'Assign Record'), ('action_add_tag', 'Add Tag'), ('action_wait', 'Wait / Delay'), ('condition', 'Condition (Branch)'), ('approval', 'Approval Gate'), ('loop', 'Loop'), ('parallel', 'Parallel Split'), ('join', 'Join / Merge')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('is_entry', models.BooleanField(default=False)),
                ('on_error', models.CharField(choices=[('stop', 'Stop'), ('continue', 'Continue'), ('retry', 'Retry')], default='stop', max_length=20)),
                ('retry_config', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'workflow_steps',
                'indexes': [models.Index(fields=['workflow_id'], name='workflow_st_workflo_db832c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(db_index=True)),
                ('step_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('waiting_approval', 'Waiting Approval')], default='pending', max_length=25)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'workflow_step_runs',
                'indexes': [models.Index(fields=['run_id'], name='workflow_st_run_id_5df99b_idx')],
            },
        ),
    ]
