# Generated by Django 5.2.15 on 2026-06-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_alter_workflowstep_step_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("action_update_record", "Update Record"),
                    ("action_create_record", "Create Record"),
                    ("action_delete_record", "Delete Record"),
                    ("action_send_email", "Send Email"),
                    ("action_send_notification", "Send In-App Notification"),
                    ("action_send_webhook", "Send Webhook"),
                    ("action_call_api", "HTTP API Call"),
                    ("action_run_workflow", "Run Sub-Workflow"),
                    ("action_run_script", "Run Server Script"),
                    ("action_assign", "Assign Record"),
                    ("action_add_tag", "Add Tag"),
                    ("action_post_journal", "Post Journal Entry"),
                    ("action_generate_document", "Generate Document"),
                    ("action_wait", "Wait / Delay"),
                    ("condition", "Condition (Branch)"),
                    ("approval", "Approval Gate"),
                    ("loop", "Loop"),
                    ("parallel", "Parallel Split"),
                    ("join", "Join / Merge"),
                ],
                max_length=50,
            ),
        ),
    ]
