# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplacePlugin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('crm', 'CRM'), ('hr', 'HR'), ('finance', 'Finance'), ('project', 'Project Management'), ('inventory', 'Inventory'), ('support', 'Support'), ('marketing', 'Marketing'), ('integration', 'Integration'), ('utility', 'Utility')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('deprecated', 'Deprecated'), ('removed', 'Removed')], default='draft', max_length=20)),
                ('publisher_id', models.UUIDField(blank=True, null=True)),
                ('publisher_name', models.CharField(blank=True, max_length=255)),
                ('is_official', models.BooleanField(default=False)),
                ('latest_version', models.CharField(blank=True, max_length=30)),
                ('install_count', models.IntegerField(default=0)),
                ('rating_sum', models.IntegerField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('icon_url', models.CharField(blank=True, max_length=2000)),
                ('screenshots', models.JSONField(default=list)),
                ('documentation_url', models.CharField(blank=True, max_length=2000)),
                ('source_url', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'db_table': 'marketplace_plugins',
            },
        ),
        migrations.CreateModel(
            name='InstalledPlugin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('plugin_id', models.UUIDField(db_index=True)),
                ('plugin_version_id', models.UUIDField(db_index=True)),
                ('plugin_slug', models.CharField(max_length=100)),
                ('installed_version', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('installing', 'Installing'), ('active', 'Active'), ('error', 'Error'), ('disabled', 'Disabled'), ('uninstalling', 'Uninstalling')], default='installing', max_length=20)),
                ('installed_by', models.UUIDField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('created_module_ids', models.JSONField(default=list)),
                ('created_entity_ids', models.JSONField(default=list)),
                ('created_workflow_ids', models.JSONField(default=list)),
                ('created_rule_ids', models.JSONField(default=list)),
                ('created_report_ids', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'installed_plugins',
                'unique_together': {('workspace_id', 'plugin_slug')},
            },
        ),
        migrations.CreateModel(
            name='PluginVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plugin_id', models.UUIDField(db_index=True)),
                ('version', models.CharField(max_length=30)),
                ('changelog', models.TextField(blank=True)),
                ('manifest', models.JSONField()),
                ('manifest_hash', models.CharField(max_length=64)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plugin_versions',
                'unique_together': {('plugin_id', 'version')},
            },
        ),
    ]
