line-length = 120
target-version = "py312"
src = ["apps", "config"]

[lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "C4", "DTZ", "T20", "SIM"]
ignore = ["E501", "B008", "N806", "N812"]

[lint.isort]
known-first-party = ["apps", "config"]

[lint.per-file-ignores]
"**/migrations/*.py" = ["E501", "F401", "N806"]
"**/tests/**" = ["S101"]
