# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('template_id', models.UUIDField(blank=True, null=True)),
                ('recipient_id', models.UUIDField(db_index=True)),
                ('recipient_type', models.CharField(choices=[('member', 'Member'), ('portal_user', 'Portal User')], default='member', max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], default='in_app', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=2000)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('record_id', models.UUIDField(blank=True, null=True)),
                ('group_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['workspace_id', 'recipient_id', 'status'], name='notificatio_workspa_06b366_idx'), models.Index(fields=['workspace_id', 'recipient_id', 'read_at'], name='notificatio_workspa_a8e33c_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('member_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=20)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification_preferences',
                'unique_together': {('workspace_id', 'member_id', 'event_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS'), ('webhook', 'Webhook')], max_length=20)),
                ('subject_template', models.CharField(blank=True, max_length=500)),
                ('body_template', models.TextField()),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notification_templates',
                'unique_together': {('workspace_id', 'slug', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField()),
                ('member_id', models.UUIDField(db_index=True)),
                ('endpoint', models.TextField()),
                ('keys_ref', models.CharField(blank=True, max_length=255)),
                ('device_label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'push_subscriptions',
                'indexes': [models.Index(fields=['member_id', 'is_active'], name='push_subscr_member__abdc6d_idx')],
            },
        ),
    ]
