# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedFieldCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('field_id', models.UUIDField(db_index=True)),
                ('record_id', models.UUIDField(db_index=True)),
                ('cached_value', models.JSONField(blank=True, null=True)),
                ('is_stale', models.BooleanField(db_index=True, default=False)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('dep_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'computed_field_cache',
                'indexes': [models.Index(fields=['workspace_id', 'is_stale'], name='computed_fi_workspa_e8bf76_idx')],
                'unique_together': {('workspace_id', 'field_id', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='ComputedFieldDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('computed_field_id', models.UUIDField(db_index=True)),
                ('dep_entity_id', models.UUIDField()),
                ('dep_field_id', models.UUIDField(db_index=True)),
                ('dep_relationship_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'computed_field_dependencies',
                'indexes': [models.Index(fields=['dep_field_id'], name='computed_fi_dep_fie_f7f15b_idx')],
                'unique_together': {('computed_field_id', 'dep_entity_id', 'dep_field_id')},
            },
        ),
    ]
