# Generated by Django 5.2.15 on 2026-06-28 08:16

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_remaining_table_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("role", models.CharField(default="member", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("invited_by", models.UUIDField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_by", models.UUIDField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="tenancy.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_invitations",
                "indexes": [
                    models.Index(
                        fields=["workspace", "status"],
                        name="workspace_i_workspa_814b7e_idx",
                    ),
                    models.Index(
                        fields=["email", "status"], name="workspace_i_email_03d7f7_idx"
                    ),
                ],
            },
        ),
    ]
