# Generated by Django 5.2.15 on 2026-07-04 09:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RevenueSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("number", models.CharField(blank=True, max_length=64)),
                ("source_module", models.CharField(blank=True, max_length=50)),
                ("source_ref", models.CharField(blank=True, max_length=128)),
                (
                    "external_ref",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                ("partner_ref", models.CharField(blank=True, max_length=128)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("straight_line", "Straight Line"),
                            ("milestone", "Milestone"),
                        ],
                        default="straight_line",
                        max_length=16,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "recognized_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("num_periods", models.PositiveIntegerField(default=1)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("frequency", models.CharField(default="monthly", max_length=12)),
                ("deferred_account", models.CharField(max_length=32)),
                ("revenue_account", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "revenue_schedules",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "status"],
                        name="revenue_sch_workspa_639f79_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "source_module", "source_ref"],
                        name="revenue_sch_workspa_d612ca_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "external_ref"],
                        name="revenue_sch_workspa_ba15e1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RevenueScheduleLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("period_no", models.PositiveIntegerField(default=1)),
                ("period_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("recognized", models.BooleanField(default=False)),
                ("journal_entry_id", models.UUIDField(blank=True, null=True)),
                ("recognized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="revenue.revenueschedule",
                    ),
                ),
            ],
            options={
                "db_table": "revenue_schedule_lines",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "schedule", "period_no"],
                        name="revenue_sch_workspa_fe8602_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "recognized", "period_date"],
                        name="revenue_sch_workspa_4be647_idx",
                    ),
                ],
            },
        ),
    ]
