# Generated by Django 5.2.15 on 2026-07-04 10:41

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialDimension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.SlugField(max_length=32)),
                ("name", models.CharField(max_length=120)),
                (
                    "dimension_type",
                    models.CharField(
                        choices=[
                            ("cost_center", "Cost Center"),
                            ("profit_center", "Profit Center"),
                            ("business_unit", "Business Unit"),
                            ("department", "Department"),
                            ("division", "Division"),
                            ("segment", "Segment"),
                            ("geography", "Geography"),
                            ("fund", "Fund"),
                            ("grant", "Grant"),
                            ("program", "Program"),
                            ("project", "Project"),
                            ("channel", "Channel"),
                            ("product_line", "Product Line"),
                            ("location", "Location"),
                            ("other", "Custom / Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_hierarchical", models.BooleanField(default=False)),
                ("allow_posting", models.BooleanField(default=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "financial_dimensions",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "code"],
                        name="financial_d_workspa_4a2cbb_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "dimension_type"],
                        name="financial_d_workspa_b635f0_idx",
                    ),
                ],
                "unique_together": {("workspace_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="FinancialDimensionValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="dimensions.financialdimension",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="dimensions.financialdimensionvalue",
                    ),
                ),
            ],
            options={
                "db_table": "financial_dimension_values",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "dimension", "code"],
                        name="financial_d_workspa_931f86_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "dimension", "is_active"],
                        name="financial_d_workspa_5c1104_idx",
                    ),
                ],
                "unique_together": {("workspace_id", "dimension", "code")},
            },
        ),
    ]
