# Generated by Django 5.2.15 on 2026-06-22 07:28

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessBlueprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("manifest", models.JSONField(default=dict)),
                ("is_published", models.BooleanField(default=False)),
                ("install_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "process_blueprints",
                "indexes": [
                    models.Index(
                        fields=["is_published", "category"],
                        name="process_blu_is_publ_7ccdcc_idx",
                    )
                ],
            },
        ),
    ]
