# Generated by Django 5.2.15 on 2026-06-24 05:14

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstalledSolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                (
                    "solution_template_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("solution_slug", models.CharField(max_length=100)),
                ("solution_name", models.CharField(blank=True, max_length=200)),
                ("installed_version", models.CharField(default="", max_length=20)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_entity_ids", models.JSONField(default=list)),
                ("created_form_ids", models.JSONField(default=list)),
                ("created_view_ids", models.JSONField(default=list)),
                ("created_workflow_ids", models.JSONField(default=list)),
                ("created_rule_ids", models.JSONField(default=list)),
                ("created_report_ids", models.JSONField(default=list)),
                ("created_role_ids", models.JSONField(default=list)),
                ("created_dashboard_ids", models.JSONField(default=list)),
                ("created_application_ids", models.JSONField(default=list)),
                ("created_navigation_ids", models.JSONField(default=list)),
                ("created_home_layout_ids", models.JSONField(default=list)),
                ("summary", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "installed_solutions",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "status"],
                        name="installed_s_workspa_be1ee5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SolutionTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("manifest", models.JSONField(default=dict)),
                ("is_system", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("install_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "solution_templates",
                "indexes": [
                    models.Index(
                        fields=["is_published", "category"],
                        name="solution_te_is_publ_1337cc_idx",
                    )
                ],
            },
        ),
    ]
