# Generated by Django 5.2.15 on 2026-06-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solution_templates", "0003_seed_system_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="installedsolution",
            name="applied_migrations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="installedsolution",
            name="installed_manifest",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="installedsolution",
            name="previous_manifest",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
