# Generated by Django 5.2.15 on 2026-06-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solution_templates", "0004_installedsolution_applied_migrations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="installedsolution",
            name="created_extra_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
