# Generated by Django 5.2.15 on 2026-07-04 13:06

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TreasuryCounterparty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                (
                    "counterparty_type",
                    models.CharField(
                        choices=[
                            ("bank", "Bank"),
                            ("government", "Government"),
                            ("corporate", "Corporate"),
                            ("fund", "Fund"),
                            ("other", "Other"),
                        ],
                        default="bank",
                        max_length=16,
                    ),
                ),
                ("credit_rating", models.CharField(blank=True, max_length=16)),
                (
                    "exposure_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "treasury_counterparties",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "code"],
                        name="treasury_co_workspa_bec809_idx",
                    )
                ],
                "unique_together": {("workspace_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="TreasuryFacility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("number", models.CharField(blank=True, max_length=64)),
                (
                    "principal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("floating", "Floating")],
                        default="fixed",
                        max_length=8,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("reference_rate", models.CharField(blank=True, max_length=32)),
                (
                    "spread",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "compounding",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("compound", "Compound"),
                            ("effective", "Effective"),
                        ],
                        default="simple",
                        max_length=10,
                    ),
                ),
                ("day_count", models.PositiveIntegerField(default=365)),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                            ("bullet", "Bullet (at maturity)"),
                        ],
                        default="monthly",
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("company_id", models.UUIDField(blank=True, null=True)),
                ("dimensions", models.JSONField(blank=True, default=dict)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("loan", "Loan"),
                            ("overdraft", "Overdraft"),
                            ("credit_facility", "Credit Facility"),
                            ("line_of_credit", "Line of Credit"),
                            ("bridge_loan", "Bridge Loan"),
                            ("project_finance", "Project Finance"),
                        ],
                        default="loan",
                        max_length=20,
                    ),
                ),
                (
                    "facility_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "drawn_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "outstanding",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("repaid", "Repaid"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=8,
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="treasury.treasurycounterparty",
                    ),
                ),
            ],
            options={
                "db_table": "treasury_facilities",
            },
        ),
        migrations.CreateModel(
            name="TreasuryInvestment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("number", models.CharField(blank=True, max_length=64)),
                (
                    "principal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("floating", "Floating")],
                        default="fixed",
                        max_length=8,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("reference_rate", models.CharField(blank=True, max_length=32)),
                (
                    "spread",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "compounding",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("compound", "Compound"),
                            ("effective", "Effective"),
                        ],
                        default="simple",
                        max_length=10,
                    ),
                ),
                ("day_count", models.PositiveIntegerField(default=365)),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                            ("bullet", "Bullet (at maturity)"),
                        ],
                        default="monthly",
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("company_id", models.UUIDField(blank=True, null=True)),
                ("dimensions", models.JSONField(blank=True, default=dict)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("money_market", "Money Market"),
                            ("treasury_bill", "Treasury Bill"),
                            ("bond", "Bond"),
                            ("commercial_paper", "Commercial Paper"),
                            ("fund", "Fund"),
                        ],
                        default="deposit",
                        max_length=20,
                    ),
                ),
                (
                    "face_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "outstanding",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("matured", "Matured"),
                            ("redeemed", "Redeemed"),
                        ],
                        default="active",
                        max_length=8,
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="treasury.treasurycounterparty",
                    ),
                ),
            ],
            options={
                "db_table": "treasury_investments",
            },
        ),
        migrations.CreateModel(
            name="TreasuryTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("number", models.CharField(blank=True, max_length=64)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("drawdown", "Drawdown"),
                            ("principal_repayment", "Principal Repayment"),
                            ("interest_accrual", "Interest Accrual"),
                            ("interest_payment", "Interest Payment"),
                            ("investment_purchase", "Investment Purchase"),
                            ("investment_sale", "Investment Sale"),
                            ("coupon", "Coupon"),
                            ("dividend", "Dividend"),
                            ("maturity", "Maturity"),
                            ("fee", "Fee"),
                            ("fx_settlement", "FX Settlement"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("company_id", models.UUIDField(blank=True, null=True)),
                ("dimensions", models.JSONField(blank=True, default=dict)),
                (
                    "external_ref",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("posted", "Posted"),
                            ("pending", "Pending"),
                            ("reversed", "Reversed"),
                        ],
                        default="posted",
                        max_length=10,
                    ),
                ),
                ("journal_entry_id", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="treasury.treasurycounterparty",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="treasury.treasuryfacility",
                    ),
                ),
                (
                    "investment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="treasury.treasuryinvestment",
                    ),
                ),
            ],
            options={
                "db_table": "treasury_transactions",
            },
        ),
        migrations.AddIndex(
            model_name="treasuryfacility",
            index=models.Index(
                fields=["workspace_id", "facility_type", "status"],
                name="treasury_fa_workspa_51cf3b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treasuryfacility",
            index=models.Index(
                fields=["workspace_id", "counterparty"],
                name="treasury_fa_workspa_599e98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treasuryinvestment",
            index=models.Index(
                fields=["workspace_id", "investment_type", "status"],
                name="treasury_in_workspa_2b5e8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treasuryinvestment",
            index=models.Index(
                fields=["workspace_id", "counterparty"],
                name="treasury_in_workspa_296718_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treasurytransaction",
            index=models.Index(
                fields=["workspace_id", "transaction_type", "status"],
                name="treasury_tr_workspa_94ce9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treasurytransaction",
            index=models.Index(
                fields=["workspace_id", "facility"],
                name="treasury_tr_workspa_9f72cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treasurytransaction",
            index=models.Index(
                fields=["workspace_id", "investment"],
                name="treasury_tr_workspa_ee23d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treasurytransaction",
            index=models.Index(
                fields=["workspace_id", "value_date"],
                name="treasury_tr_workspa_815e49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treasurytransaction",
            index=models.Index(
                fields=["workspace_id", "external_ref"],
                name="treasury_tr_workspa_5b5839_idx",
            ),
        ),
    ]
