# Generated by Django 5.2.15 on 2026-06-24 10:18

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MRPRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("run_type", models.CharField(default="regenerative", max_length=20)),
                ("status", models.CharField(default="completed", max_length=20)),
                ("shortage_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "mfg_mrp_runs",
            },
        ),
        migrations.CreateModel(
            name="BillOfMaterials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("number", models.CharField(blank=True, max_length=64)),
                ("product_item_id", models.UUIDField(db_index=True)),
                ("revision", models.CharField(default="A", max_length=20)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "yield_percent",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "scrap_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_alternate", models.BooleanField(default=False)),
                ("status", models.CharField(default="draft", max_length=20)),
            ],
            options={
                "db_table": "mfg_boms",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "product_item_id", "status"],
                        name="mfg_boms_workspa_264a9e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BomComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("bom_id", models.UUIDField(db_index=True)),
                ("component_item_id", models.UUIDField(db_index=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "scrap_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("alternate_group", models.CharField(blank=True, max_length=32)),
                ("sequence", models.IntegerField(default=10)),
            ],
            options={
                "db_table": "mfg_bom_components",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "bom_id", "sequence"],
                        name="mfg_bom_com_workspa_1cc59d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("production_order_id", models.UUIDField(db_index=True)),
                ("component_item_id", models.UUIDField(db_index=True)),
                (
                    "required_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "reserved_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "issued_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
            ],
            options={
                "db_table": "mfg_material_reservations",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "production_order_id"],
                        name="mfg_materia_workspa_a90d06_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MRPResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("mrp_run_id", models.UUIDField(db_index=True)),
                ("item_id", models.UUIDField(db_index=True)),
                (
                    "demand",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "available",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "net_requirement",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "suggested_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                ("action", models.CharField(default="none", max_length=20)),
            ],
            options={
                "db_table": "mfg_mrp_results",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "mrp_run_id"],
                        name="mfg_mrp_res_workspa_8b6d3a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NonConformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("production_order_id", models.UUIDField(blank=True, null=True)),
                ("defect", models.CharField(max_length=255)),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                ("status", models.CharField(default="open", max_length=20)),
            ],
            options={
                "db_table": "mfg_non_conformances",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "status"],
                        name="mfg_non_con_workspa_5f8e4f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductionCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("production_order_id", models.UUIDField(db_index=True)),
                ("cost_type", models.CharField(max_length=20)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("reference", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "db_table": "mfg_production_costs",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "production_order_id", "cost_type"],
                        name="mfg_product_workspa_9841f9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductionOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("production_order_id", models.UUIDField(db_index=True)),
                ("routing_step_id", models.UUIDField(blank=True, null=True)),
                ("work_center_id", models.UUIDField(blank=True, null=True)),
                ("sequence", models.IntegerField(default=10)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_finish", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_finish", models.DateTimeField(blank=True, null=True)),
                (
                    "labor_minutes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "machine_minutes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "downtime_minutes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                ("downtime_reason", models.CharField(blank=True, max_length=40)),
                (
                    "good_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "reject_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
            ],
            options={
                "db_table": "mfg_production_operations",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "production_order_id", "sequence"],
                        name="mfg_product_workspa_ea76f0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("number", models.CharField(blank=True, max_length=64)),
                ("product_item_id", models.UUIDField(db_index=True)),
                ("bom_id", models.UUIDField(blank=True, null=True)),
                ("routing_id", models.UUIDField(blank=True, null=True)),
                ("warehouse_id", models.UUIDField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                ("priority", models.CharField(default="medium", max_length=20)),
                ("status", models.CharField(default="draft", max_length=20)),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_finish", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_finish", models.DateTimeField(blank=True, null=True)),
                (
                    "material_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "labor_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "overhead_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "good_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "scrap_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                ("journal_entry_id", models.UUIDField(blank=True, null=True)),
                ("source_project_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "mfg_production_orders",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "status", "product_item_id"],
                        name="mfg_product_workspa_f567a6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QualityCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("production_order_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "sampling_percent",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "sampled_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "passed_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "failed_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                ("result", models.CharField(default="pass", max_length=20)),
            ],
            options={
                "db_table": "mfg_quality_checks",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "production_order_id"],
                        name="mfg_quality_workspa_a829ad_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Routing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("number", models.CharField(blank=True, max_length=64)),
                ("product_item_id", models.UUIDField(db_index=True)),
                ("revision", models.CharField(default="A", max_length=20)),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "db_table": "mfg_routings",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "product_item_id"],
                        name="mfg_routing_workspa_0ddb3d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoutingStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("routing_id", models.UUIDField(db_index=True)),
                ("sequence", models.IntegerField(default=10)),
                ("work_center_id", models.UUIDField()),
                (
                    "setup_minutes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "run_minutes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "queue_minutes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "move_minutes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
            ],
            options={
                "db_table": "mfg_routing_steps",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "routing_id", "sequence"],
                        name="mfg_routing_workspa_47f584_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("item_id", models.UUIDField(db_index=True)),
                ("lot_number", models.CharField(max_length=64)),
                ("batch_number", models.CharField(blank=True, max_length=64)),
                ("serial_number", models.CharField(blank=True, max_length=64)),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("supplier_ref", models.CharField(blank=True, max_length=128)),
                ("production_order_id", models.UUIDField(blank=True, null=True)),
                ("consumed_lot_ids", models.JSONField(default=list)),
            ],
            options={
                "db_table": "mfg_stock_lots",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "item_id", "lot_number"],
                        name="mfg_stock_l_workspa_d2d742_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                ("center_type", models.CharField(default="machine", max_length=20)),
                (
                    "capacity_per_hour",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "efficiency",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "cost_per_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("asset_record_id", models.UUIDField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "mfg_work_centers",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "is_active"],
                        name="mfg_work_ce_workspa_d35085_idx",
                    )
                ],
            },
        ),
    ]
