# Generated by Django 5.2.15 on 2026-06-23 10:57

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("key", models.SlugField(max_length=100)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                ("prefix", models.CharField(blank=True, max_length=40)),
                ("suffix", models.CharField(blank=True, max_length=40)),
                ("padding", models.PositiveSmallIntegerField(default=6)),
                ("start_value", models.BigIntegerField(default=1)),
                ("increment", models.PositiveIntegerField(default=1)),
                (
                    "reset_scope",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("yearly", "Yearly"),
                            ("monthly", "Monthly"),
                            ("daily", "Daily"),
                        ],
                        default="never",
                        max_length=10,
                    ),
                ),
                ("include_period_in_format", models.BooleanField(default=False)),
                ("current_value", models.BigIntegerField(default=0)),
                ("period_key", models.CharField(blank=True, max_length=16)),
                ("initialized", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_system", models.BooleanField(default=False)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "number_sequences",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "key"],
                        name="number_sequ_workspa_169f36_idx",
                    )
                ],
                "unique_together": {("workspace_id", "key")},
            },
        ),
        migrations.CreateModel(
            name="NumberAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("key", models.SlugField(max_length=100)),
                ("formatted", models.CharField(max_length=128)),
                ("value", models.BigIntegerField()),
                ("period_key", models.CharField(blank=True, max_length=16)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("allocated_by", models.UUIDField(blank=True, null=True)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="numbering.numbersequence",
                    ),
                ),
            ],
            options={
                "db_table": "number_allocations",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "key"],
                        name="number_allo_workspa_0e3dbe_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "sequence"],
                        name="number_allo_workspa_c4faa1_idx",
                    ),
                ],
            },
        ),
    ]
