# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('api_key', 'API Key'), ('system', 'System'), ('workflow', 'Workflow'), ('portal_user', 'Portal User')], default='user', max_length=20)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_user_agent', models.CharField(blank=True, max_length=500)),
                ('http_method', models.CharField(max_length=10)),
                ('http_path', models.CharField(max_length=2000)),
                ('http_status', models.IntegerField()),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('changed_fields', models.JSONField(default=list)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('duration_ms', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['workspace_id', '-occurred_at'], name='audit_logs_workspa_257ba6_idx'), models.Index(fields=['workspace_id', 'actor_id', '-occurred_at'], name='audit_logs_workspa_3e7f00_idx'), models.Index(fields=['workspace_id', 'resource_type', 'resource_id'], name='audit_logs_workspa_71a534_idx')],
            },
        ),
    ]
