# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField()),
                ('level', models.IntegerField()),
                ('approver_id', models.UUIDField()),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'approval_decisions',
                'indexes': [models.Index(fields=['request_id', 'level'], name='approval_de_request_dc10f3_idx')],
                'unique_together': {('request_id', 'level', 'approver_id')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('trigger_condition_nql', models.TextField(blank=True)),
                ('levels', models.JSONField(default=list)),
                ('on_approve_actions', models.JSONField(default=list)),
                ('on_reject_actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'approval_processes',
                'unique_together': {('workspace_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('process_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField()),
                ('record_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('current_level', models.IntegerField(default=1)),
                ('requested_by', models.UUIDField()),
                ('resolved_by', models.UUIDField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_comment', models.TextField(blank=True)),
                ('workflow_run_id', models.UUIDField(blank=True, null=True)),
                ('step_run_id', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'approval_requests',
                'indexes': [models.Index(fields=['workspace_id', 'record_id'], name='approval_re_workspa_cb182d_idx'), models.Index(fields=['workspace_id', 'status'], name='approval_re_workspa_ee08ce_idx')],
            },
        ),
    ]
