# Generated by Django 5.2.15 on 2026-06-24 08:02

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("employee_record_id", models.UUIDField(db_index=True)),
                ("dimension", models.CharField(default="cost_center", max_length=20)),
                ("target_ref", models.CharField(max_length=64)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
            ],
            options={
                "db_table": "payroll_cost_allocations",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "employee_record_id"],
                        name="payroll_cos_workspa_78c5e4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLoan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("employee_record_id", models.UUIDField(db_index=True)),
                ("reference", models.CharField(blank=True, max_length=64)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "installment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "db_table": "payroll_loans",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "employee_record_id", "status"],
                        name="payroll_loa_workspa_764563_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeePayrollProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("employee_record_id", models.UUIDField(db_index=True)),
                ("payroll_status", models.CharField(default="active", max_length=20)),
                ("bank_account", models.CharField(blank=True, max_length=64)),
                ("bank_name", models.CharField(blank=True, max_length=150)),
                ("iban", models.CharField(blank=True, max_length=64)),
                ("payment_method", models.CharField(default="bank", max_length=20)),
                ("cost_center", models.CharField(blank=True, max_length=64)),
                ("currency", models.CharField(default="", max_length=8)),
                ("payroll_calendar_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "payroll_employee_profiles",
                "unique_together": {("workspace_id", "employee_record_id")},
            },
        ),
        migrations.CreateModel(
            name="EmploymentContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("employee_record_id", models.UUIDField(db_index=True)),
                ("contract_number", models.CharField(blank=True, max_length=64)),
                ("contract_type", models.CharField(default="permanent", max_length=20)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "db_table": "payroll_contracts",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "employee_record_id", "status"],
                        name="payroll_con_workspa_679d71_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FinalSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("employee_record_id", models.UUIDField(db_index=True)),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "leave_encashment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "benefits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "gratuity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "loans",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "advances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "penalties",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("status", models.CharField(default="draft", max_length=20)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "payroll_final_settlements",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "employee_record_id"],
                        name="payroll_fin_workspa_c8e4a8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FXRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("from_currency", models.CharField(max_length=8)),
                ("to_currency", models.CharField(max_length=8)),
                (
                    "rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=16),
                ),
                ("effective_date", models.DateField()),
            ],
            options={
                "db_table": "payroll_fx_rates",
                "indexes": [
                    models.Index(
                        fields=[
                            "workspace_id",
                            "from_currency",
                            "to_currency",
                            "-effective_date",
                        ],
                        name="payroll_fx__workspa_63646d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OvertimeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("employee_record_id", models.UUIDField(db_index=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "multiplier",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                ("status", models.CharField(default="submitted", max_length=20)),
                ("payroll_period_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "payroll_overtime",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "employee_record_id", "status"],
                        name="payroll_ove_workspa_558a59_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("employee_record_id", models.UUIDField(db_index=True)),
                ("payroll_period_id", models.UUIDField(blank=True, null=True)),
                ("adj_type", models.CharField(default="bonus", max_length=20)),
                ("code", models.CharField(blank=True, max_length=64)),
                ("name", models.CharField(blank=True, max_length=150)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("reason", models.TextField(blank=True)),
                ("status", models.CharField(default="pending", max_length=20)),
            ],
            options={
                "db_table": "payroll_adjustments",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "employee_record_id", "status"],
                        name="payroll_adj_workspa_ed50a7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollCalendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=150)),
                ("frequency", models.CharField(default="monthly", max_length=20)),
                ("processing_date", models.DateField(blank=True, null=True)),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("cutoff_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payroll_calendars",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "is_active"],
                        name="payroll_cal_workspa_52a4bc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("processing", "Processing"),
                            ("closed", "Closed"),
                            ("locked", "Locked"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("payroll_calendar_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "payroll_periods",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "status", "start_date"],
                        name="payroll_per_workspa_fe0cce_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("payroll_period_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                            ("cancelled", "Cancelled"),
                            ("locked", "Locked"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("started_by", models.UUIDField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.UUIDField(blank=True, null=True)),
                ("posted_by", models.UUIDField(blank=True, null=True)),
                ("journal_entry_id", models.UUIDField(blank=True, null=True)),
                (
                    "total_gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "total_net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("employee_count", models.IntegerField(default=0)),
                ("is_retro", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "payroll_runs",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "payroll_period_id", "status"],
                        name="payroll_run_workspa_6e169b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("frequency", models.CharField(default="monthly", max_length=20)),
                ("currency", models.CharField(default="", max_length=8)),
                ("default_country", models.CharField(default="", max_length=8)),
                ("default_cost_center", models.CharField(blank=True, max_length=64)),
                ("pay_start_day", models.IntegerField(default=1)),
                ("pay_end_day", models.IntegerField(default=31)),
            ],
            options={
                "db_table": "payroll_settings",
                "indexes": [
                    models.Index(
                        fields=["workspace_id"], name="payroll_set_workspa_74a246_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("payroll_run_id", models.UUIDField(db_index=True)),
                ("data", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "payroll_snapshots",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "payroll_run_id"],
                        name="payroll_sna_workspa_152359_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("number", models.CharField(blank=True, max_length=64)),
                ("employee_record_id", models.UUIDField(db_index=True)),
                ("payroll_period_id", models.UUIDField(db_index=True)),
                ("payroll_run_id", models.UUIDField(db_index=True)),
                ("currency", models.CharField(default="", max_length=8)),
                (
                    "fx_rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=16),
                ),
                (
                    "gross_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "net_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("cost_center", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                            ("paid", "Paid"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("snapshot", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "payroll_payslips",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "payroll_run_id"],
                        name="payroll_pay_workspa_c0af37_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "employee_record_id"],
                        name="payroll_pay_workspa_3da055_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PayslipLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("payslip_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("earning", "Earning"),
                            ("deduction", "Deduction"),
                            ("benefit", "Benefit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("formula_version", models.IntegerField(default=0)),
                ("source", models.CharField(default="computed", max_length=20)),
                ("sequence", models.IntegerField(default=100)),
            ],
            options={
                "db_table": "payroll_payslip_lines",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "payslip_id", "sequence"],
                        name="payroll_pay_workspa_0fa75a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SalaryAdvance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("employee_record_id", models.UUIDField(db_index=True)),
                ("reference", models.CharField(blank=True, max_length=64)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "installment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "db_table": "payroll_advances",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "employee_record_id", "status"],
                        name="payroll_adv_workspa_85bd4c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=150)),
                ("currency", models.CharField(default="", max_length=8)),
                ("country", models.CharField(default="", max_length=8)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "db_table": "payroll_salary_structures",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "status"],
                        name="payroll_sal_workspa_3e073f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SalaryStructureAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("employee_record_id", models.UUIDField(db_index=True)),
                ("salary_structure_id", models.UUIDField(db_index=True)),
                ("effective_date", models.DateField()),
                (
                    "base_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("is_current", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payroll_structure_assignments",
                "indexes": [
                    models.Index(
                        fields=[
                            "workspace_id",
                            "employee_record_id",
                            "-effective_date",
                        ],
                        name="payroll_str_workspa_60036a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StructureComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("salary_structure_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("earning", "Earning"),
                            ("deduction", "Deduction"),
                            ("benefit", "Benefit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("calc_type", models.CharField(default="fixed", max_length=20)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("formula", models.TextField(blank=True)),
                ("formula_version", models.IntegerField(default=1)),
                ("base_code", models.CharField(blank=True, max_length=64)),
                ("taxable", models.BooleanField(default=True)),
                ("gl_account_code", models.CharField(blank=True, max_length=32)),
                ("sequence", models.IntegerField(default=100)),
            ],
            options={
                "db_table": "payroll_structure_components",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "salary_structure_id", "sequence"],
                        name="payroll_str_workspa_ffb89f_idx",
                    )
                ],
            },
        ),
    ]
