# Generated by Django 5.2.15 on 2026-06-22 05:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("key", models.SlugField(max_length=100)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=False)),
                ("rollout_percent", models.IntegerField(default=100)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("role", "Role"),
                            ("user", "User"),
                            ("global", "Global"),
                        ],
                        default="workspace",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "feature_flags",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "key"],
                        name="feature_fla_workspa_05b26a_idx",
                    )
                ],
                "unique_together": {("workspace_id", "key")},
            },
        ),
        migrations.CreateModel(
            name="FeatureFlagOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("role", "Role"),
                            ("user", "User"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="feature_flags.featureflag",
                    ),
                ),
            ],
            options={
                "db_table": "feature_flag_overrides",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "flag"],
                        name="feature_fla_workspa_c80ca3_idx",
                    )
                ],
                "unique_together": {
                    ("workspace_id", "flag", "target_type", "target_id")
                },
            },
        ),
    ]
