# Generated by Django 5.2.15 on 2026-06-23 11:19

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountingPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("locked", "Locked"),
                        ],
                        default="open",
                        max_length=8,
                    ),
                ),
                ("fiscal_year", models.CharField(blank=True, max_length=16)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "ledger_periods",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "code"],
                        name="ledger_peri_workspa_804a1b_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "start_date", "end_date"],
                        name="ledger_peri_workspa_f6dc1b_idx",
                    ),
                ],
                "unique_together": {("workspace_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("entry_number", models.CharField(blank=True, max_length=64)),
                ("date", models.DateField()),
                ("memo", models.CharField(blank=True, max_length=500)),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                        ],
                        default="draft",
                        max_length=8,
                    ),
                ),
                ("source_module", models.CharField(blank=True, max_length=50)),
                ("source_ref", models.CharField(blank=True, max_length=128)),
                ("posting_rule_key", models.CharField(blank=True, max_length=100)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("posted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="ledger.accountingperiod",
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_by_entries",
                        to="ledger.journalentry",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_journal_entries",
            },
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                        ],
                        max_length=12,
                    ),
                ),
                ("is_group", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("description", models.TextField(blank=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ledger.ledgeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_accounts",
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("line_no", models.PositiveIntegerField(default=0)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("memo", models.CharField(blank=True, max_length=500)),
                ("partner_ref", models.CharField(blank=True, max_length=128)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="ledger.ledgeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_journal_lines",
            },
        ),
        migrations.CreateModel(
            name="PostingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("event_type", models.CharField(max_length=100)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("template", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "ledger_posting_rules",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "event_type"],
                        name="ledger_post_workspa_f76127_idx",
                    )
                ],
                "unique_together": {("workspace_id", "event_type")},
            },
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["workspace_id", "status"], name="ledger_jour_workspa_861f03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["workspace_id", "date"], name="ledger_jour_workspa_9c6f32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["workspace_id", "source_module", "source_ref"],
                name="ledger_jour_workspa_51f81c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgeraccount",
            index=models.Index(
                fields=["workspace_id", "code"], name="ledger_acco_workspa_776862_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgeraccount",
            index=models.Index(
                fields=["workspace_id", "account_type"],
                name="ledger_acco_workspa_077df6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ledgeraccount",
            unique_together={("workspace_id", "code")},
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["workspace_id", "entry"], name="ledger_jour_workspa_4c0967_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["workspace_id", "account"],
                name="ledger_jour_workspa_42f3f4_idx",
            ),
        ),
    ]
