# Generated by Django 5.2.15 on 2026-06-24 15:23

import uuid

import django.utils.timezone
from django.db import migrations, models

_TABLE = "ledger_accounting_settings"
_POLICY = "workspace_isolation"


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cur:
        cur.execute(f'ALTER TABLE "{_TABLE}" ENABLE ROW LEVEL SECURITY;')
        cur.execute(f'ALTER TABLE "{_TABLE}" FORCE ROW LEVEL SECURITY;')
        cur.execute(f'DROP POLICY IF EXISTS "{_POLICY}" ON "{_TABLE}";')
        cur.execute(
            f'CREATE POLICY "{_POLICY}" ON "{_TABLE}" '
            f"USING (workspace_id = "
            f"NULLIF(current_setting('app.workspace_id', TRUE), '')::uuid);"
        )


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cur:
        cur.execute(f'DROP POLICY IF EXISTS "{_POLICY}" ON "{_TABLE}";')
        cur.execute(f'ALTER TABLE "{_TABLE}" DISABLE ROW LEVEL SECURITY;')


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_ledger_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                (
                    "default_cash_account",
                    models.CharField(default="1000", max_length=32),
                ),
                (
                    "default_receivable_account",
                    models.CharField(default="1100", max_length=32),
                ),
                (
                    "default_inventory_account",
                    models.CharField(default="1200", max_length=32),
                ),
                (
                    "default_finished_goods_account",
                    models.CharField(default="1400", max_length=32),
                ),
                (
                    "default_fixed_asset_account",
                    models.CharField(default="1500", max_length=32),
                ),
                (
                    "default_accumulated_depreciation_account",
                    models.CharField(default="1600", max_length=32),
                ),
                (
                    "default_wip_account",
                    models.CharField(default="1700", max_length=32),
                ),
                (
                    "default_payable_account",
                    models.CharField(default="2000", max_length=32),
                ),
                (
                    "default_grni_account",
                    models.CharField(default="2050", max_length=32),
                ),
                (
                    "default_revenue_account",
                    models.CharField(default="4000", max_length=32),
                ),
                (
                    "default_cogs_account",
                    models.CharField(default="5000", max_length=32),
                ),
                (
                    "default_depreciation_expense_account",
                    models.CharField(default="6300", max_length=32),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "ledger_accounting_settings",
                "indexes": [
                    models.Index(
                        fields=["workspace_id"], name="ledger_acco_workspa_c3e315_idx"
                    )
                ],
                "unique_together": {("workspace_id",)},
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
