# Generated by Django 5.2.15 on 2026-07-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_accountingsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingsettings",
            name="default_discount_account",
            field=models.CharField(default="4200", max_length=32),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="default_late_fee_income_account",
            field=models.CharField(default="4900", max_length=32),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="default_refund_account",
            field=models.CharField(default="4100", max_length=32),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="default_scholarship_account",
            field=models.CharField(default="6700", max_length=32),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="default_writeoff_account",
            field=models.CharField(default="6800", max_length=32),
        ),
    ]
