# Generated by Django 5.2.15 on 2026-07-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_accountingsettings_default_discount_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingsettings",
            name="default_input_tax_account",
            field=models.CharField(default="1450", max_length=32),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="default_output_tax_account",
            field=models.CharField(default="2210", max_length=32),
        ),
    ]
