# Generated by Django 5.2.15 on 2026-07-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_accountingsettings_default_input_tax_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalline",
            name="base_credit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="journalline",
            name="base_debit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="journalline",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="journalline",
            name="fx_rate",
            field=models.DecimalField(decimal_places=8, default=1, max_digits=20),
        ),
    ]
