# Generated by Django 5.2.15 on 2026-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0007_backfill_base_amounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingsettings",
            name="default_fx_gain_account",
            field=models.CharField(default="4930", max_length=32),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="default_fx_loss_account",
            field=models.CharField(default="6960", max_length=32),
        ),
    ]
