# Generated by Django 5.2.15 on 2026-07-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0008_accountingsettings_default_fx_gain_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalline",
            name="dimensions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
