# Generated by Django 5.2.15 on 2026-07-04 12:00

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0009_journalline_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingsettings",
            name="default_cta_account",
            field=models.CharField(default="3900", max_length=32),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="default_ic_payable_account",
            field=models.CharField(default="2900", max_length=32),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="default_ic_receivable_account",
            field=models.CharField(default="1900", max_length=32),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="company_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="ledger_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("company_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=120)),
                (
                    "ledger_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary / Statutory"),
                            ("ifrs", "IFRS"),
                            ("local_gaap", "Local GAAP"),
                            ("tax", "Tax"),
                            ("management", "Management"),
                        ],
                        default="primary",
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("is_primary", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "ledgers",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "company_id", "is_primary"],
                        name="ledgers_workspa_509136_idx",
                    )
                ],
                "unique_together": {("workspace_id", "code")},
            },
        ),
    ]
