# Generated by Django 5.2.15 on 2026-07-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0012_backfill_default_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingsettings",
            name="default_borrowing_account",
            field=models.CharField(default="2600", max_length=32),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="default_interest_expense_account",
            field=models.CharField(default="6500", max_length=32),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="default_interest_income_account",
            field=models.CharField(default="4920", max_length=32),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="default_investment_account",
            field=models.CharField(default="1250", max_length=32),
        ),
    ]
