# Generated by Django 5.2.15 on 2026-07-04 10:07

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=3)),
                ("name", models.CharField(blank=True, max_length=64)),
                ("symbol", models.CharField(blank=True, max_length=8)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                ("is_base", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "currencies",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "code"],
                        name="currencies_workspa_557aa0_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "is_base"],
                        name="currencies_workspa_066c5b_idx",
                    ),
                ],
                "unique_together": {("workspace_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("from_currency", models.CharField(max_length=3)),
                ("to_currency", models.CharField(max_length=3)),
                (
                    "rate",
                    models.DecimalField(decimal_places=8, default=1, max_digits=20),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("spot", "Spot"),
                            ("average", "Average"),
                            ("closing", "Closing"),
                            ("historical", "Historical"),
                        ],
                        default="spot",
                        max_length=12,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "exchange_rates",
                "indexes": [
                    models.Index(
                        fields=[
                            "workspace_id",
                            "from_currency",
                            "to_currency",
                            "effective_date",
                        ],
                        name="exchange_ra_workspa_9683bc_idx",
                    )
                ],
            },
        ),
    ]
