# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSMTPConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('host', models.CharField(max_length=253)),
                ('port', models.IntegerField(default=587)),
                ('username', models.CharField(max_length=255)),
                ('password_ref', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_result', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'email_smtp_configs',
                'unique_together': {('workspace_id',)},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('logo_url', models.CharField(blank=True, max_length=2000)),
                ('favicon_url', models.CharField(blank=True, max_length=2000)),
                ('app_name', models.CharField(blank=True, max_length=100)),
                ('color_primary', models.CharField(default='#6366f1', max_length=7)),
                ('color_secondary', models.CharField(default='#8b5cf6', max_length=7)),
                ('color_accent', models.CharField(default='#06b6d4', max_length=7)),
                ('color_background', models.CharField(default='#ffffff', max_length=7)),
                ('color_surface', models.CharField(default='#f8fafc', max_length=7)),
                ('color_text_primary', models.CharField(default='#0f172a', max_length=7)),
                ('color_text_muted', models.CharField(default='#64748b', max_length=7)),
                ('font_family_heading', models.CharField(default='Inter', max_length=100)),
                ('font_family_body', models.CharField(default='Inter', max_length=100)),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('allow_theme_toggle', models.BooleanField(default=True)),
                ('custom_css', models.TextField(blank=True)),
                ('login_headline', models.CharField(blank=True, max_length=255)),
                ('login_subtext', models.CharField(blank=True, max_length=500)),
                ('login_background_url', models.CharField(blank=True, max_length=2000)),
                ('email_from_name', models.CharField(blank=True, max_length=100)),
                ('email_header_html', models.TextField(blank=True)),
                ('email_footer_html', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'workspace_branding',
                'unique_together': {('workspace_id',)},
            },
        ),
    ]
