# Generated by Django 5.2.15 on 2026-07-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacebranding",
            name="border_radius",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("sm", "Small"),
                    ("md", "Medium"),
                    ("lg", "Large"),
                    ("xl", "Extra Large"),
                ],
                default="md",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="workspacebranding",
            name="ui_density",
            field=models.CharField(
                choices=[("comfortable", "Comfortable"), ("compact", "Compact")],
                default="comfortable",
                max_length=12,
            ),
        ),
    ]
