# Generated by Django 5.2.15 on 2026-07-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branding", "0002_workspacebranding_border_radius_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacebranding",
            name="locked_fields",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
