# Generated by Django 5.2.15 on 2026-06-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_mfa_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="grace_period_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="rotated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="passkey_credentials",
            field=models.JSONField(default=list),
        ),
    ]
