# Generated by Django 5.2.15 on 2026-06-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_apikey_grace_period_ends_at_apikey_rotated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationtoken",
            name="new_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
