# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMaskingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('field_id', models.UUIDField()),
                ('role_id', models.UUIDField()),
                ('mask_type', models.CharField(max_length=30)),
                ('mask_pattern', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'data_masking_rules',
            },
        ),
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('field_id', models.UUIDField(db_index=True)),
                ('role_id', models.UUIDField(db_index=True)),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'field_permissions',
                'unique_together': {('field_id', 'role_id')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=63)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permissions.role')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('resource_type', models.CharField(choices=[('workspace', 'Workspace'), ('module', 'Module'), ('entity', 'Entity'), ('field', 'Field'), ('record', 'Record'), ('report', 'Report'), ('workflow', 'Workflow'), ('dashboard', 'Dashboard'), ('document', 'Document')], max_length=30)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('import', 'Import'), ('share', 'Share'), ('admin', 'Admin'), ('*', 'All')], max_length=30)),
                ('is_deny', models.BooleanField(default=False)),
                ('conditions', models.JSONField(default=list)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permissions.role')),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['workspace_id', 'is_active'], name='roles_workspa_b430b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('workspace_id', 'slug')},
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['role', 'resource_type', 'action'], name='permissions_role_id_02b653_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['workspace_id', 'resource_type'], name='permissions_workspa_0b0094_idx'),
        ),
    ]
