# Generated by Django 5.2.15 on 2026-07-04 12:12

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                ("functional_currency", models.CharField(blank=True, max_length=3)),
                ("is_group", models.BooleanField(default=False)),
                ("is_elimination", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("legal_registration", models.CharField(blank=True, max_length=64)),
                ("fiscal_calendar_ref", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="CompanyOwnership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                (
                    "ownership_pct",
                    models.DecimalField(decimal_places=4, default=100, max_digits=7),
                ),
                (
                    "voting_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("subsidiary", "Subsidiary"),
                            ("associate", "Associate"),
                            ("joint_venture", "Joint Venture"),
                            ("minority", "Minority"),
                        ],
                        default="subsidiary",
                        max_length=16,
                    ),
                ),
                ("is_direct", models.BooleanField(default=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "parent_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owns",
                        to="companies.company",
                    ),
                ),
                (
                    "subsidiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_by",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_ownership",
            },
        ),
        migrations.CreateModel(
            name="CompanyTaxRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("vat", "VAT"),
                            ("gst", "GST"),
                            ("corporate_tax", "Corporate Tax"),
                            ("payroll_tax", "Payroll Tax"),
                            ("import", "Import"),
                            ("export", "Export"),
                            ("withholding", "Withholding"),
                            ("other", "Other"),
                        ],
                        default="vat",
                        max_length=20,
                    ),
                ),
                ("authority", models.CharField(blank=True, max_length=120)),
                ("jurisdiction", models.CharField(blank=True, max_length=64)),
                ("registration_number", models.CharField(blank=True, max_length=64)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_registrations",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_tax_registrations",
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["workspace_id", "code"], name="companies_workspa_ec5427_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["workspace_id", "parent"], name="companies_workspa_f05709_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["workspace_id", "is_default"],
                name="companies_workspa_44b5b2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="company",
            unique_together={("workspace_id", "code")},
        ),
        migrations.AddIndex(
            model_name="companyownership",
            index=models.Index(
                fields=["workspace_id", "subsidiary", "effective_from"],
                name="company_own_workspa_4b07a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companyownership",
            index=models.Index(
                fields=["workspace_id", "parent_company"],
                name="company_own_workspa_66ccf8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companytaxregistration",
            index=models.Index(
                fields=["workspace_id", "company", "tax_type"],
                name="company_tax_workspa_431636_idx",
            ),
        ),
    ]
