# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('custom_domain', models.CharField(blank=True, max_length=253)),
                ('logo_url', models.CharField(blank=True, max_length=2000)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('exposed_entity_ids', models.JSONField(default=list)),
                ('default_role_id', models.UUIDField(blank=True, null=True)),
                ('allow_self_signup', models.BooleanField(default=False)),
                ('signup_domain_whitelist', models.JSONField(default=list)),
                ('welcome_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'portal_configurations',
                'unique_together': {('workspace_id',)},
            },
        ),
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal_user_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('family_id', models.UUIDField(unique=True)),
                ('current_jti', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'portal_sessions',
                'indexes': [models.Index(fields=['portal_user_id', 'is_active'], name='portal_sess_portal__e3913a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(blank=True, max_length=2000)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=255)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('linked_entity_id', models.UUIDField(blank=True, null=True)),
                ('linked_record_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('role_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'portal_users',
                'unique_together': {('workspace_id', 'email')},
            },
        ),
        migrations.CreateModel(
            name='PortalUserToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal_user_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField()),
                ('token_type', models.CharField(choices=[('email_verify', 'Email Verification'), ('password_reset', 'Password Reset'), ('invite', 'Invite')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'portal_user_tokens',
                'indexes': [models.Index(fields=['portal_user_id', 'token_type'], name='portal_user_portal__fd6b2f_idx')],
            },
        ),
    ]
