# Generated by Django 5.2.15 on 2026-06-22 07:23

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portaluser",
            name="portal_type",
            field=models.CharField(default="customer", max_length=30),
        ),
        migrations.CreateModel(
            name="PortalEntityGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("entity_slug", models.SlugField(max_length=63)),
                (
                    "portal_type",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("link_field", models.SlugField(max_length=63)),
                ("can_read", models.BooleanField(default=True)),
                ("can_create", models.BooleanField(default=False)),
                ("can_update", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "portal_entity_grants",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "entity_slug"],
                        name="portal_enti_workspa_72a320_idx",
                    )
                ],
                "unique_together": {("workspace_id", "entity_slug", "portal_type")},
            },
        ),
    ]
