# Generated by Django 5.2.15 on 2026-07-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_portal_grant_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalentitygrant",
            name="link_source",
            field=models.SlugField(blank=True, default="", max_length=63),
        ),
    ]
