# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('record_id', models.UUIDField(db_index=True)),
                ('activity_type', models.CharField(choices=[('record_created', 'Record Created'), ('record_updated', 'Record Updated'), ('record_deleted', 'Record Deleted'), ('record_restored', 'Record Restored'), ('field_changed', 'Field Changed'), ('comment_added', 'Comment Added'), ('comment_edited', 'Comment Edited'), ('comment_deleted', 'Comment Deleted'), ('file_attached', 'File Attached'), ('file_removed', 'File Removed'), ('relationship_linked', 'Relationship Linked'), ('relationship_unlinked', 'Relationship Unlinked'), ('workflow_started', 'Workflow Started'), ('workflow_completed', 'Workflow Completed'), ('workflow_failed', 'Workflow Failed'), ('approval_requested', 'Approval Requested'), ('approval_approved', 'Approved'), ('approval_rejected', 'Rejected'), ('assignment_changed', 'Assigned'), ('stage_changed', 'Stage Changed'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('sla_warning', 'SLA Warning'), ('sla_breached', 'SLA Breached'), ('sla_met', 'SLA Met'), ('email_sent', 'Email Sent'), ('note_added', 'Note Added'), ('custom', 'Custom')], max_length=30)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('workflow', 'Workflow'), ('api_key', 'API Key'), ('portal_user', 'Portal User')], default='user', max_length=20)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField()),
                ('changes', models.JSONField(default=list)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('event_sequence', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('is_pinned', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'activity_entries',
                'indexes': [models.Index(fields=['workspace_id', 'record_id', '-occurred_at'], name='activity_en_workspa_f31106_idx'), models.Index(fields=['workspace_id', 'entity_id', '-occurred_at'], name='activity_en_workspa_5a976b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField()),
                ('record_id', models.UUIDField(db_index=True)),
                ('author_id', models.UUIDField()),
                ('author_type', models.CharField(choices=[('member', 'Member'), ('portal_user', 'Portal User')], default='member', max_length=20)),
                ('parent_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('body', models.TextField()),
                ('body_format', models.CharField(choices=[('markdown', 'Markdown'), ('plain', 'Plain')], default='markdown', max_length=10)),
                ('mentions', models.JSONField(default=list)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comments',
                'indexes': [models.Index(fields=['workspace_id', 'record_id', 'created_at'], name='comments_workspa_852084_idx'), models.Index(fields=['parent_id'], name='comments_parent__9f8798_idx')],
            },
        ),
    ]
