# Generated by Django 5.2.15 on 2026-06-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
