# Generated by Django 5.2.15 on 2026-07-04 11:36

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("budget", "Budget"), ("forecast", "Forecast")],
                        default="budget",
                        max_length=10,
                    ),
                ),
                ("fiscal_year", models.CharField(blank=True, max_length=16)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("is_rolling", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("locked", "Locked"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "financial_plans",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "plan_type", "status"],
                        name="financial_p_workspa_4e8aa8_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "fiscal_year"],
                        name="financial_p_workspa_675948_idx",
                    ),
                ],
                "unique_together": {("workspace_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="PlanVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("version_no", models.PositiveIntegerField(default=1)),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("baseline", "Baseline"),
                            ("working", "Working"),
                            ("optimistic", "Optimistic"),
                            ("pessimistic", "Pessimistic"),
                            ("committed", "Committed"),
                        ],
                        default="baseline",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("locked", "Locked"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("revision_note", models.CharField(blank=True, max_length=500)),
                ("is_current", models.BooleanField(default=True)),
                ("submitted_by", models.UUIDField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="budgets.financialplan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_versions",
            },
        ),
        migrations.CreateModel(
            name="PlanLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("account_code", models.CharField(max_length=32)),
                ("dimensions", models.JSONField(blank=True, default=dict)),
                ("period", models.CharField(blank=True, max_length=16)),
                ("period_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="budgets.planversion",
                    ),
                ),
            ],
            options={
                "db_table": "plan_lines",
            },
        ),
        migrations.AddIndex(
            model_name="planversion",
            index=models.Index(
                fields=["workspace_id", "plan", "scenario", "is_current"],
                name="plan_versio_workspa_e29800_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planversion",
            unique_together={("workspace_id", "plan", "scenario", "version_no")},
        ),
        migrations.AddIndex(
            model_name="planline",
            index=models.Index(
                fields=["workspace_id", "version", "account_code"],
                name="plan_lines_workspa_6fa594_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planline",
            index=models.Index(
                fields=["workspace_id", "version", "period_date"],
                name="plan_lines_workspa_89785a_idx",
            ),
        ),
    ]
