# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityLabelTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('locale', models.CharField(max_length=10)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('field_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('singular', models.CharField(blank=True, max_length=255)),
                ('plural', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'entity_label_translations',
                'unique_together': {('workspace_id', 'locale', 'entity_id', 'field_id')},
            },
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=255)),
                ('default_value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'translation_keys',
                'unique_together': {('namespace', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TranslationOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('key_id', models.UUIDField(db_index=True)),
                ('locale', models.CharField(max_length=10)),
                ('value', models.TextField()),
                ('updated_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'translation_overrides',
                'indexes': [models.Index(fields=['workspace_id', 'locale'], name='translation_workspa_4c4566_idx')],
                'unique_together': {('workspace_id', 'key_id', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceLocale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('default_locale', models.CharField(default='en-US', max_length=10)),
                ('default_timezone', models.CharField(default='UTC', max_length=63)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('enabled_locales', models.JSONField(default=list)),
                ('date_format', models.CharField(blank=True, max_length=30)),
                ('time_format', models.CharField(blank=True, max_length=20)),
                ('number_decimal_separator', models.CharField(default='.', max_length=1)),
                ('number_thousands_separator', models.CharField(default=',', max_length=1)),
            ],
            options={
                'db_table': 'workspace_locales',
                'unique_together': {('workspace_id',)},
            },
        ),
    ]
