# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True, unique=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('locked_by', models.UUIDField()),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('session_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'record_locks',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('entity_slug', models.CharField(db_index=True, max_length=63)),
                ('custom_data', models.JSONField(default=dict)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('_event_version', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'records',
                'indexes': [models.Index(fields=['workspace_id', 'entity_id'], name='records_workspa_1e9885_idx'), models.Index(fields=['workspace_id', 'entity_slug'], name='records_workspa_5c61cf_idx'), models.Index(fields=['deleted_at'], name='records_deleted_6c5cb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecordVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('version_number', models.IntegerField()),
                ('snapshot', models.JSONField()),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'record_versions',
                'indexes': [models.Index(fields=['record_id', '-version_number'], name='record_vers_record__441ed5_idx')],
                'unique_together': {('record_id', 'version_number')},
            },
        ),
    ]
