# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=63)),
                ('schedule', models.JSONField(default=dict)),
                ('holidays', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'business_hours',
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('applies_when_nql', models.TextField(blank=True)),
                ('targets', models.JSONField(default=list)),
                ('escalation_actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sla_policies',
                'unique_together': {('workspace_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SLARecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField()),
                ('record_id', models.UUIDField(db_index=True)),
                ('metric_key', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('warning', 'Warning'), ('breached', 'Breached'), ('met', 'Met'), ('paused', 'Paused')], default='on_track', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('target_at', models.DateTimeField()),
                ('warning_at', models.DateTimeField()),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('met_at', models.DateTimeField(blank=True, null=True)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
                ('paused_seconds', models.IntegerField(default=0)),
                ('warning_sent', models.BooleanField(default=False)),
                ('breach_notified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sla_records',
                'indexes': [models.Index(fields=['workspace_id', 'status'], name='sla_records_workspa_57ac29_idx'), models.Index(fields=['target_at'], name='sla_records_target__4ab517_idx')],
                'unique_together': {('workspace_id', 'record_id', 'policy_id', 'metric_key')},
            },
        ),
    ]
