# Generated by Django 5.2.15 on 2026-06-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sla", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesshours",
            name="region",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="businesshours",
            name="shifts",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="businesshours",
            name="weekly_hours",
            field=models.JSONField(default=dict),
        ),
    ]
