# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('base_url', models.URLField(max_length=2000)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('api_key_header', 'API Key (Header)'), ('api_key_query', 'API Key (Query Param)'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth'), ('oauth2_client_credentials', 'OAuth2 Client Credentials')], default='none', max_length=30)),
                ('auth_config', models.JSONField(default=dict)),
                ('default_headers', models.JSONField(default=dict)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'http_connectors',
                'unique_together': {('workspace_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='InboundWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('workflow_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_ips', models.JSONField(default=list)),
                ('expected_content_type', models.CharField(blank=True, max_length=127)),
                ('call_count', models.BigIntegerField(default=0)),
                ('last_called_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inbound_webhooks',
                'unique_together': {('workspace_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='OAuthApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('slack', 'Slack'), ('github', 'GitHub'), ('custom', 'Custom OAuth2')], max_length=30)),
                ('client_id', models.CharField(max_length=500)),
                ('client_secret_ref', models.CharField(max_length=255)),
                ('scopes', models.JSONField(default=list)),
                ('redirect_uri', models.CharField(blank=True, max_length=2000)),
                ('extra_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'oauth_apps',
                'unique_together': {('workspace_id', 'provider', 'client_id')},
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('event_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=10)),
                ('attempt_number', models.IntegerField(default=1)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('request_headers', models.JSONField(default=dict)),
                ('request_body_hash', models.CharField(blank=True, max_length=64)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body_snippet', models.CharField(blank=True, max_length=500)),
                ('duration_ms', models.IntegerField(default=0)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'indexes': [models.Index(fields=['subscription_id', '-delivered_at'], name='webhook_del_subscri_8f8fc4_idx'), models.Index(fields=['status', 'next_retry_at'], name='webhook_del_status_741062_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('target_url', models.URLField(max_length=2000)),
                ('signing_secret_ref', models.CharField(blank=True, max_length=255)),
                ('event_types', models.JSONField(default=list)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled_too_many_errors', 'Disabled (Errors)')], default='active', max_length=30)),
                ('http_method', models.CharField(default='POST', max_length=10)),
                ('headers', models.JSONField(default=dict)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('max_retries', models.IntegerField(default=3)),
                ('success_count', models.BigIntegerField(default=0)),
                ('failure_count', models.BigIntegerField(default=0)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'webhook_subscriptions',
                'indexes': [models.Index(fields=['workspace_id', 'status'], name='webhook_sub_workspa_75be7b_idx')],
            },
        ),
    ]
