# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('folder_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=127)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('storage_key', models.CharField(max_length=1024)),
                ('storage_backend', models.CharField(choices=[('local', 'Local'), ('s3', 'S3')], default='local', max_length=20)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error'), ('quarantined', 'Quarantined')], default='uploading', max_length=20)),
                ('av_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('av_clean', models.BooleanField(blank=True, null=True)),
                ('current_version', models.IntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('record_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'documents',
                'indexes': [models.Index(fields=['workspace_id', 'folder_id'], name='documents_workspa_3baaeb_idx'), models.Index(fields=['workspace_id', 'record_id'], name='documents_workspa_ba2a90_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('path', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'document_folders',
                'indexes': [models.Index(fields=['workspace_id', 'parent_id'], name='document_fo_workspa_351868_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('share_type', models.CharField(choices=[('member', 'Member'), ('team', 'Team'), ('public_link', 'Public Link'), ('portal_user', 'Portal User')], max_length=20)),
                ('recipient_id', models.UUIDField(blank=True, null=True)),
                ('permission', models.CharField(choices=[('view', 'View'), ('comment', 'Comment'), ('edit', 'Edit')], max_length=10)),
                ('token', models.CharField(blank=True, max_length=100, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'document_shares',
                'indexes': [models.Index(fields=['document_id'], name='document_sh_documen_bc141e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('version_number', models.IntegerField()),
                ('storage_key', models.CharField(max_length=1024)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('uploaded_by', models.UUIDField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'document_versions',
                'unique_together': {('document_id', 'version_number')},
            },
        ),
    ]
