# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('backup_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('config_only', 'Config Only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='queued', max_length=20)),
                ('initiated_by', models.UUIDField(blank=True, null=True)),
                ('is_automatic', models.BooleanField(default=False)),
                ('storage_key', models.CharField(blank=True, max_length=1024)),
                ('storage_backend', models.CharField(default='local', max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('encryption_key_ref', models.CharField(blank=True, max_length=255)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('from_event_sequence', models.BigIntegerField(blank=True, null=True)),
                ('to_event_sequence', models.BigIntegerField(blank=True, null=True)),
                ('entity_count', models.IntegerField(default=0)),
                ('record_count', models.BigIntegerField(default=0)),
                ('document_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'backup_jobs',
                'indexes': [models.Index(fields=['workspace_id', 'status'], name='backup_jobs_workspa_8e3161_idx'), models.Index(fields=['workspace_id', '-created_at'], name='backup_jobs_workspa_062ab9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField(db_index=True, unique=True)),
                ('entity_slug', models.CharField(max_length=63)),
                ('retain_days', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('soft_delete', 'Soft Delete'), ('hard_delete', 'Hard Delete'), ('anonymize', 'Anonymize'), ('archive', 'Archive to Cold Storage')], default='soft_delete', max_length=20)),
                ('anonymize_fields', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_enforced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_retention_policies',
                'indexes': [models.Index(fields=['workspace_id', 'is_active'], name='data_retent_workspa_1d49c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('restore_type', models.CharField(choices=[('full_backup', 'Full Backup'), ('pitr', 'Point-in-Time Recovery')], max_length=20)),
                ('backup_job_id', models.UUIDField(blank=True, null=True)),
                ('pitr_target_sequence', models.BigIntegerField(blank=True, null=True)),
                ('pitr_target_timestamp', models.DateTimeField(blank=True, null=True)),
                ('target_workspace_id', models.UUIDField()),
                ('target_workspace_slug', models.CharField(max_length=63)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('initiated_by', models.UUIDField()),
                ('confirmation_token_hash', models.CharField(blank=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'restore_jobs',
                'indexes': [models.Index(fields=['workspace_id', '-created_at'], name='restore_job_workspa_c7a601_idx')],
            },
        ),
    ]
