# Generated by Django 5.2.15 on 2026-07-04 12:00

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsolidationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("group_company_id", models.UUIDField(db_index=True)),
                ("group_code", models.CharField(blank=True, max_length=32)),
                ("as_of", models.DateField(blank=True, null=True)),
                ("presentation_currency", models.CharField(blank=True, max_length=3)),
                ("version_no", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("dry_run", "Dry Run"), ("final", "Final")],
                        default="final",
                        max_length=8,
                    ),
                ),
                ("balanced", models.BooleanField(default=False)),
                ("company_count", models.PositiveIntegerField(default=0)),
                ("worksheet", models.JSONField(blank=True, default=dict)),
                (
                    "cta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_minority_interest",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "consolidation_runs",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "group_company_id", "as_of"],
                        name="consolidati_workspa_ee2c7b_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "status"],
                        name="consolidati_workspa_ad6b58_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MinorityInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("company_id", models.UUIDField()),
                ("company_code", models.CharField(blank=True, max_length=32)),
                (
                    "ownership_pct",
                    models.DecimalField(decimal_places=4, default=100, max_digits=7),
                ),
                (
                    "minority_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "net_assets",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "minority_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("as_of", models.DateField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minorities",
                        to="consolidation.consolidationrun",
                    ),
                ),
            ],
            options={
                "db_table": "minority_interests",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "run"],
                        name="minority_in_workspa_e35ab6_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "company_id"],
                        name="minority_in_workspa_831380_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TranslationAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("company_id", models.UUIDField()),
                ("company_code", models.CharField(blank=True, max_length=32)),
                ("from_currency", models.CharField(blank=True, max_length=3)),
                ("to_currency", models.CharField(blank=True, max_length=3)),
                (
                    "closing_rate",
                    models.DecimalField(decimal_places=8, default=1, max_digits=20),
                ),
                (
                    "average_rate",
                    models.DecimalField(decimal_places=8, default=1, max_digits=20),
                ),
                (
                    "cta_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="consolidation.consolidationrun",
                    ),
                ),
            ],
            options={
                "db_table": "translation_adjustments",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "run"],
                        name="translation_workspa_22b65d_idx",
                    )
                ],
            },
        ),
    ]
