# Generated by Django 5.2.15 on 2026-07-04 12:26

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consolidation", "0002_consolidation_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsolidationWorksheetLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("company_code", models.CharField(blank=True, max_length=32)),
                ("account_code", models.CharField(max_length=32)),
                ("account_type", models.CharField(blank=True, max_length=12)),
                (
                    "functional_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "translated_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "eliminated_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("is_cta", models.BooleanField(default=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worksheet_lines",
                        to="consolidation.consolidationrun",
                    ),
                ),
            ],
            options={
                "db_table": "consolidation_worksheet_lines",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "run", "company_code"],
                        name="consolidati_workspa_b4633c_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "run", "account_code"],
                        name="consolidati_workspa_aede94_idx",
                    ),
                ],
            },
        ),
    ]
