# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('member_id', models.UUIDField(db_index=True)),
                ('query_text', models.CharField(max_length=500)),
                ('entity_slug', models.CharField(blank=True, max_length=63)),
                ('result_count', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recent_searches',
                'indexes': [models.Index(fields=['workspace_id', 'member_id', '-searched_at'], name='recent_sear_workspa_094e69_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('nql_ast', models.JSONField()),
                ('nql_source', models.TextField(blank=True)),
                ('created_by', models.UUIDField()),
                ('is_shared', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'saved_searches',
                'indexes': [models.Index(fields=['workspace_id', 'entity_id', 'created_by'], name='saved_searc_workspa_c13eb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField(db_index=True, unique=True)),
                ('entity_slug', models.CharField(max_length=63)),
                ('indexed_field_slugs', models.JSONField(default=list)),
                ('field_weights', models.JSONField(default=dict)),
                ('config_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_reindex_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_row_count', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'search_indexes',
                'indexes': [models.Index(fields=['workspace_id'], name='search_inde_workspa_e4ede2_idx')],
            },
        ),
    ]
