# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projection_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('last_sequence', models.BigIntegerField(default=0)),
                ('last_event_id', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'projection_checkpoints',
            },
        ),
        migrations.CreateModel(
            name='AggregateSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('version', models.BigIntegerField()),
                ('state', models.JSONField()),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'aggregate_snapshots',
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id', '-version'], name='aggregate_s_aggrega_960927_idx')],
                'unique_together': {('aggregate_type', 'aggregate_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField()),
                ('workspace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('result_event_ids', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('dispatched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'command_log',
                'indexes': [models.Index(fields=['workspace_id', 'command_type'], name='command_log_workspa_12ac95_idx'), models.Index(fields=['dispatched_at'], name='command_log_dispatc_75c17a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('global_sequence', models.BigIntegerField(db_index=True, editable=False, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('event_version', models.SmallIntegerField(default=1)),
                ('aggregate_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('payload', models.JSONField()),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_type', models.CharField(default='user', max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'domain_events',
                'ordering': ['global_sequence'],
                'indexes': [models.Index(fields=['workspace_id', 'aggregate_type', 'aggregate_id'], name='domain_even_workspa_9ac4a0_idx'), models.Index(fields=['workspace_id', 'event_type'], name='domain_even_workspa_8f0f8b_idx'), models.Index(fields=['occurred_at'], name='domain_even_occurre_e69e84_idx'), models.Index(fields=['correlation_id'], name='domain_even_correla_67d43d_idx')],
            },
        ),
    ]
