# Generated by Django 5.2.15 on 2026-06-22 06:30

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("included_entity_ids", models.JSONField(default=list)),
                ("navigation_id", models.UUIDField(blank=True, null=True)),
                ("home_layout_id", models.UUIDField(blank=True, null=True)),
                ("role_ids", models.JSONField(default=list)),
                ("theme_overrides", models.JSONField(default=dict)),
                ("order", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "studio_applications",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "is_published"],
                        name="studio_appl_workspa_4c7fb0_idx",
                    )
                ],
                "unique_together": {("workspace_id", "slug")},
            },
        ),
        migrations.CreateModel(
            name="HomeLayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("app", "Application"),
                            ("role", "Role"),
                            ("personal", "Personal"),
                        ],
                        default="workspace",
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("widgets", models.JSONField(default=list)),
                ("is_published", models.BooleanField(default=False)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "studio_home_layouts",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "scope"],
                        name="studio_home_workspa_4e2e02_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Navigation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("app", "Application"),
                            ("role", "Role"),
                        ],
                        default="workspace",
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("tree", models.JSONField(default=list)),
                ("is_published", models.BooleanField(default=False)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "studio_navigations",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "scope"],
                        name="studio_navi_workspa_6edf8b_idx",
                    )
                ],
            },
        ),
    ]
