# Generated by Django 5.2.15 on 2026-07-04 07:50

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxAuthority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("level", models.CharField(blank=True, max_length=16)),
                ("registration_no", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "tax_authorities",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "code"],
                        name="tax_authori_workspa_d2ced8_idx",
                    )
                ],
                "unique_together": {("workspace_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="TaxCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("vat", "VAT"),
                            ("gst", "GST"),
                            ("sales_tax", "Sales Tax"),
                            ("excise", "Excise"),
                            ("service_tax", "Service Tax"),
                            ("withholding", "Withholding Tax"),
                            ("custom", "Custom / Other"),
                        ],
                        default="vat",
                        max_length=16,
                    ),
                ),
                ("is_inclusive", models.BooleanField(default=False)),
                ("is_compound", models.BooleanField(default=False)),
                ("is_recoverable", models.BooleanField(default=True)),
                ("is_withholding", models.BooleanField(default=False)),
                (
                    "rounding",
                    models.CharField(
                        choices=[
                            ("half_up", "Half Up"),
                            ("half_down", "Half Down"),
                            ("half_even", "Half Even"),
                        ],
                        default="half_up",
                        max_length=10,
                    ),
                ),
                ("output_account_code", models.CharField(blank=True, max_length=32)),
                ("input_account_code", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="codes",
                        to="taxes.taxauthority",
                    ),
                ),
            ],
            options={
                "db_table": "tax_codes",
            },
        ),
        migrations.CreateModel(
            name="TaxGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "tax_groups",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "code"],
                        name="tax_groups_workspa_40baaa_idx",
                    )
                ],
                "unique_together": {("workspace_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="TaxExemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("partner_ref", models.CharField(max_length=128)),
                ("certificate_no", models.CharField(blank=True, max_length=64)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exemptions",
                        to="taxes.taxcode",
                    ),
                ),
                (
                    "tax_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exemptions",
                        to="taxes.taxgroup",
                    ),
                ),
            ],
            options={
                "db_table": "tax_exemptions",
            },
        ),
        migrations.CreateModel(
            name="TaxGroupMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "tax_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_members",
                        to="taxes.taxcode",
                    ),
                ),
                (
                    "tax_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="taxes.taxgroup",
                    ),
                ),
            ],
            options={
                "db_table": "tax_group_members",
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "tax_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="taxes.taxcode",
                    ),
                ),
            ],
            options={
                "db_table": "tax_rates",
            },
        ),
        migrations.CreateModel(
            name="TaxTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("source_module", models.CharField(blank=True, max_length=50)),
                ("source_ref", models.CharField(blank=True, max_length=128)),
                ("tax_code_str", models.CharField(blank=True, max_length=32)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("output", "Output (collected)"),
                            ("input", "Input (paid/recoverable)"),
                        ],
                        default="output",
                        max_length=8,
                    ),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("is_recoverable", models.BooleanField(default=True)),
                ("is_exempt", models.BooleanField(default=False)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("partner_ref", models.CharField(blank=True, max_length=128)),
                ("jurisdiction", models.CharField(blank=True, max_length=64)),
                (
                    "external_ref",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("computed", "Computed"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                        ],
                        default="computed",
                        max_length=10,
                    ),
                ),
                ("journal_entry_id", models.UUIDField(blank=True, null=True)),
                ("reversal_entry_id", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="taxes.taxcode",
                    ),
                ),
            ],
            options={
                "db_table": "tax_transactions",
            },
        ),
        migrations.AddIndex(
            model_name="taxcode",
            index=models.Index(
                fields=["workspace_id", "code"], name="tax_codes_workspa_eb3017_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxcode",
            index=models.Index(
                fields=["workspace_id", "tax_type"], name="tax_codes_workspa_a29906_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxcode",
            unique_together={("workspace_id", "code")},
        ),
        migrations.AddIndex(
            model_name="taxexemption",
            index=models.Index(
                fields=["workspace_id", "partner_ref"],
                name="tax_exempti_workspa_d623dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxgroupmember",
            index=models.Index(
                fields=["workspace_id", "tax_group", "sequence"],
                name="tax_group_m_workspa_877be1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxrate",
            index=models.Index(
                fields=["workspace_id", "tax_code", "effective_from"],
                name="tax_rates_workspa_a69c75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxtransaction",
            index=models.Index(
                fields=["workspace_id", "direction", "status"],
                name="tax_transac_workspa_2a10d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxtransaction",
            index=models.Index(
                fields=["workspace_id", "source_module", "source_ref"],
                name="tax_transac_workspa_c48a0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxtransaction",
            index=models.Index(
                fields=["workspace_id", "external_ref"],
                name="tax_transac_workspa_5a840d_idx",
            ),
        ),
    ]
