# Generated by Django 5.2.15 on 2026-07-04 10:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("bank", "Bank"),
                            ("cash", "Cash"),
                            ("mobile_money", "Mobile Money"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        default="bank",
                        max_length=16,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=200)),
                ("account_number", models.CharField(blank=True, max_length=64)),
                ("iban", models.CharField(blank=True, max_length=64)),
                ("swift", models.CharField(blank=True, max_length=32)),
                ("gl_account_code", models.CharField(blank=True, max_length=32)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "cash_bank_accounts",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "code"],
                        name="cash_bank_a_workspa_8e8d74_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "gl_account_code"],
                        name="cash_bank_a_workspa_1c7e45_idx",
                    ),
                ],
                "unique_together": {("workspace_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("statement_ref", models.CharField(blank=True, max_length=64)),
                ("statement_date", models.DateField(blank=True, null=True)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "external_ref",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("imported", "Imported"),
                            ("reconciling", "Reconciling"),
                            ("reconciled", "Reconciled"),
                        ],
                        default="imported",
                        max_length=12,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="cash.bankaccount",
                    ),
                ),
            ],
            options={
                "db_table": "bank_statements",
            },
        ),
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("reconciliation_date", models.DateField(blank=True, null=True)),
                (
                    "book_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "statement_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "reconciled_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "difference",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("reconciled", "Reconciled"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("reconciled_by", models.UUIDField(blank=True, null=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="cash.bankaccount",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliations",
                        to="cash.bankstatement",
                    ),
                ),
            ],
            options={
                "db_table": "bank_reconciliations",
            },
        ),
        migrations.CreateModel(
            name="BankStatementLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("line_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "In (receipt)"), ("out", "Out (payment)")],
                        default="in",
                        max_length=4,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=128)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("counterparty", models.CharField(blank=True, max_length=200)),
                (
                    "matched_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Unmatched"),
                            ("matched", "Matched"),
                            ("ignored", "Ignored"),
                        ],
                        default="unmatched",
                        max_length=10,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stmt_lines",
                        to="cash.bankaccount",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="cash.bankstatement",
                    ),
                ),
            ],
            options={
                "db_table": "bank_statement_lines",
            },
        ),
        migrations.CreateModel(
            name="BankTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("number", models.CharField(blank=True, max_length=64)),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("bank_to_bank", "Bank to Bank"),
                            ("cash_to_bank", "Cash to Bank"),
                            ("bank_to_cash", "Bank to Cash"),
                            ("cash_to_cash", "Cash to Cash"),
                        ],
                        default="bank_to_bank",
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("transfer_date", models.DateField(blank=True, null=True)),
                ("memo", models.CharField(blank=True, max_length=255)),
                (
                    "external_ref",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                ("journal_entry_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "from_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="cash.bankaccount",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="cash.bankaccount",
                    ),
                ),
            ],
            options={
                "db_table": "bank_transfers",
            },
        ),
        migrations.CreateModel(
            name="CashInstrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("number", models.CharField(blank=True, max_length=64)),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("cheque_issued", "Cheque Issued"),
                            ("cheque_received", "Cheque Received"),
                            ("deposit", "Deposit"),
                            ("eft", "EFT"),
                            ("wire", "Wire"),
                            ("card", "Card"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        default="cheque_received",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "In (receipt)"), ("out", "Out (payment)")],
                        default="in",
                        max_length=4,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=128)),
                ("counterparty", models.CharField(blank=True, max_length=200)),
                ("partner_ref", models.CharField(blank=True, max_length=128)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("clearing_date", models.DateField(blank=True, null=True)),
                ("journal_entry_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("deposited", "Deposited"),
                            ("cleared", "Cleared"),
                            ("bounced", "Bounced"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments",
                        to="cash.bankaccount",
                    ),
                ),
            ],
            options={
                "db_table": "cash_instruments",
            },
        ),
        migrations.CreateModel(
            name="ReconciliationMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("journal_line_id", models.UUIDField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("reference", "Reference"),
                            ("tolerance", "Tolerance"),
                            ("partial", "Partial"),
                            ("manual", "Manual"),
                        ],
                        default="exact",
                        max_length=12,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="cash.bankaccount",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="cash.bankreconciliation",
                    ),
                ),
                (
                    "statement_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="cash.bankstatementline",
                    ),
                ),
            ],
            options={
                "db_table": "reconciliation_matches",
            },
        ),
        migrations.AddIndex(
            model_name="bankstatement",
            index=models.Index(
                fields=["workspace_id", "bank_account", "statement_date"],
                name="bank_statem_workspa_6f44dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatement",
            index=models.Index(
                fields=["workspace_id", "external_ref"],
                name="bank_statem_workspa_88b630_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliation",
            index=models.Index(
                fields=["workspace_id", "bank_account", "status"],
                name="bank_reconc_workspa_cd0fc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatementline",
            index=models.Index(
                fields=["workspace_id", "statement", "status"],
                name="bank_statem_workspa_e87fb4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatementline",
            index=models.Index(
                fields=["workspace_id", "bank_account", "line_date"],
                name="bank_statem_workspa_202178_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="banktransfer",
            index=models.Index(
                fields=["workspace_id", "status"], name="bank_transf_workspa_47d2db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransfer",
            index=models.Index(
                fields=["workspace_id", "external_ref"],
                name="bank_transf_workspa_00e749_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashinstrument",
            index=models.Index(
                fields=["workspace_id", "bank_account", "status"],
                name="cash_instru_workspa_64a142_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashinstrument",
            index=models.Index(
                fields=["workspace_id", "instrument_type", "status"],
                name="cash_instru_workspa_3ad342_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationmatch",
            index=models.Index(
                fields=["workspace_id", "reconciliation"],
                name="reconciliat_workspa_b5a0b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationmatch",
            index=models.Index(
                fields=["workspace_id", "journal_line_id"],
                name="reconciliat_workspa_2e54f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationmatch",
            index=models.Index(
                fields=["workspace_id", "statement_line"],
                name="reconciliat_workspa_8981e2_idx",
            ),
        ),
    ]
