# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('tag_id', models.UUIDField(db_index=True)),
                ('document_id', models.UUIDField(db_index=True)),
                ('attached_by', models.UUIDField(blank=True, null=True)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_tags',
                'unique_together': {('workspace_id', 'tag_id', 'document_id')},
            },
        ),
        migrations.CreateModel(
            name='RecordTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('tag_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField()),
                ('record_id', models.UUIDField(db_index=True)),
                ('attached_by', models.UUIDField(blank=True, null=True)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'record_tags',
                'indexes': [models.Index(fields=['workspace_id', 'record_id'], name='record_tags_workspa_14f4fa_idx')],
                'unique_together': {('workspace_id', 'tag_id', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('group', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'tags',
                'indexes': [models.Index(fields=['workspace_id', 'group'], name='tags_workspa_593b13_idx')],
                'unique_together': {('workspace_id', 'slug')},
            },
        ),
    ]
