# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('report_id', models.UUIDField(blank=True, null=True)),
                ('initiated_by', models.UUIDField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=15)),
                ('nql_ast', models.JSONField(blank=True, null=True)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('json', 'JSON')], default='csv', max_length=10)),
                ('include_fields', models.JSONField(default=list)),
                ('output_storage_key', models.CharField(blank=True, max_length=1024)),
                ('output_filename', models.CharField(blank=True, max_length=500)),
                ('row_count', models.IntegerField(default=0)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('download_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'export_jobs',
                'indexes': [models.Index(fields=['workspace_id', '-created_at'], name='export_jobs_workspa_378b8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('entity_slug', models.CharField(max_length=63)),
                ('initiated_by', models.UUIDField()),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('parsing', 'Parsing'), ('validating', 'Validating'), ('awaiting_confirm', 'Awaiting Confirmation'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploading', max_length=25)),
                ('source_filename', models.CharField(max_length=500)),
                ('source_storage_key', models.CharField(blank=True, max_length=1024)),
                ('source_mime_type', models.CharField(blank=True, max_length=127)),
                ('column_mapping', models.JSONField(default=dict)),
                ('delimiter', models.CharField(default=',', max_length=5)),
                ('has_header', models.BooleanField(default=True)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=50)),
                ('encoding', models.CharField(default='utf-8', max_length=20)),
                ('duplicate_strategy', models.CharField(choices=[('skip', 'Skip'), ('update', 'Update'), ('error', 'Error')], default='skip', max_length=10)),
                ('match_field_slug', models.CharField(blank=True, max_length=100)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('invalid_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'import_jobs',
                'indexes': [models.Index(fields=['workspace_id', 'entity_id', '-created_at'], name='import_jobs_workspa_50e50c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('mapped_data', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('imported', 'Imported'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=10)),
                ('imported_record_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_rows',
                'indexes': [models.Index(fields=['job_id', 'status'], name='import_rows_job_id_ef34d0_idx')],
                'unique_together': {('job_id', 'row_number')},
            },
        ),
    ]
