# Generated by Django 5.0.6 on 2026-06-20 11:57

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineageEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('source_node_id', models.UUIDField(db_index=True)),
                ('target_node_id', models.UUIDField(db_index=True)),
                ('edge_type', models.CharField(choices=[('reads', 'Reads'), ('writes', 'Writes'), ('triggers', 'Triggers'), ('produces', 'Produces'), ('consumes', 'Consumes'), ('derives_from', 'Derives From'), ('references', 'References')], max_length=20)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'lineage_edges',
                'indexes': [models.Index(fields=['workspace_id', 'source_node_id'], name='lineage_edg_workspa_fbb4a5_idx'), models.Index(fields=['workspace_id', 'target_node_id'], name='lineage_edg_workspa_716dfc_idx')],
                'unique_together': {('workspace_id', 'source_node_id', 'target_node_id', 'edge_type')},
            },
        ),
        migrations.CreateModel(
            name='LineageNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('node_type', models.CharField(choices=[('entity', 'Entity Definition'), ('field', 'Field Definition'), ('record', 'Record'), ('report', 'Report'), ('dashboard', 'Dashboard'), ('widget', 'Dashboard Widget'), ('workflow', 'Workflow'), ('workflow_step', 'Workflow Step'), ('import_job', 'Import Job'), ('export_job', 'Export Job'), ('api_endpoint', 'API Endpoint'), ('form', 'Public Form')], max_length=25)),
                ('object_id', models.UUIDField(db_index=True)),
                ('object_slug', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'lineage_nodes',
                'indexes': [models.Index(fields=['workspace_id', 'node_type'], name='lineage_nod_workspa_3121d8_idx')],
                'unique_together': {('workspace_id', 'node_type', 'object_id')},
            },
        ),
    ]
