# Generated by Django 5.2.15 on 2026-07-04 09:46

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SettlementDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("partner_ref", models.CharField(max_length=128)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("debit", "Debit (owed — invoice/charge)"),
                            ("credit", "Credit (paying — payment/credit)"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("charge", "Charge"),
                            ("debit_note", "Debit Note"),
                            ("payment", "Payment"),
                            ("credit_note", "Credit Note"),
                            ("deposit", "Deposit"),
                            ("advance", "Advance"),
                            ("refund", "Refund"),
                        ],
                        default="invoice",
                        max_length=16,
                    ),
                ),
                ("document_ref", models.CharField(blank=True, max_length=128)),
                ("document_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("account_code", models.CharField(blank=True, max_length=32)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("source_module", models.CharField(blank=True, max_length=50)),
                (
                    "external_ref",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("partial", "Partial"),
                            ("settled", "Settled"),
                            ("void", "Void"),
                        ],
                        default="open",
                        max_length=8,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "settlement_documents",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "partner_ref", "direction", "status"],
                        name="settlement__workspa_905f39_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "external_ref"],
                        name="settlement__workspa_d1c012_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "document_date"],
                        name="settlement__workspa_c07ccd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "external_ref",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "credit_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations_from",
                        to="settlement.settlementdocument",
                    ),
                ),
                (
                    "debit_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations_to",
                        to="settlement.settlementdocument",
                    ),
                ),
            ],
            options={
                "db_table": "settlement_allocations",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "credit_document"],
                        name="settlement__workspa_67fa3f_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "debit_document"],
                        name="settlement__workspa_fc66a8_idx",
                    ),
                ],
            },
        ),
    ]
