# Generated by Django 5.2.15 on 2026-07-01 05:32

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("discount", "Discount"),
                            ("scholarship", "Scholarship"),
                            ("waiver", "Fee Waiver"),
                            ("credit_note", "Credit Note"),
                            ("refund", "Refund"),
                            ("write_off", "Write-off"),
                        ],
                        default="discount",
                        max_length=20,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=64)),
                ("subject_ref", models.CharField(blank=True, max_length=64)),
                ("applies_to_ref", models.CharField(blank=True, max_length=64)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("reason", models.TextField(blank=True)),
                ("gl_debit_account", models.CharField(max_length=32)),
                ("gl_credit_account", models.CharField(max_length=32)),
                (
                    "external_ref",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("posted", "Posted"), ("void", "Void")],
                        default="posted",
                        max_length=10,
                    ),
                ),
                ("journal_entry_id", models.UUIDField(blank=True, null=True)),
                ("reversal_entry_id", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "credit_notes",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "kind", "status"],
                        name="credit_note_workspa_8c36cb_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "applies_to_ref"],
                        name="credit_note_workspa_a5f53c_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "subject_ref"],
                        name="credit_note_workspa_5515ca_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "external_ref"],
                        name="credit_note_workspa_65554b_idx",
                    ),
                ],
            },
        ),
    ]
